<?php

namespace Database\Seeders;

use App\Models\Commune;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CommuneSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $communes = [
            ['id' => 1, 'district_id' => 1, 'name' => 'Tonle Basak'],
            ['id' => 2, 'district_id' => 1, 'name' => 'Boeng Trabek'],
            ['id' => 3, 'district_id' => 1, 'name' => 'Phsar Doeum Thkov'],
            ['id' => 4, 'district_id' => 1, 'name' => 'Toul Tum Poung 1'],
            ['id' => 5, 'district_id' => 1, 'name' => 'Toul Tum Poung 2'],
            ['id' => 6, 'district_id' => 2, 'name' => 'Sraas Chak'],
            ['id' => 7, 'district_id' => 2, 'name' => 'Wat Phnom'],
            ['id' => 8, 'district_id' => 2, 'name' => 'Phsar Chas'],
            ['id' => 9, 'district_id' => 2, 'name' => 'Phsar Kandal 1'],
            ['id' => 10, 'district_id' => 2, 'name' => 'Phsar Kandal 2'],
            ['id' => 11, 'district_id' => 2, 'name' => 'Chey Chumneas'],
            ['id' => 12, 'district_id' => 2, 'name' => 'Chak Tomuk'],
            ['id' => 13, 'district_id' => 2, 'name' => 'Phsar Thmei 1'],
            ['id' => 14, 'district_id' => 2, 'name' => 'Phsar Thmei 2'],
            ['id' => 15, 'district_id' => 2, 'name' => 'Phsar Thmei 3'],
            ['id' => 16, 'district_id' => 2, 'name' => 'Boeng Raing'],
            ['id' => 17, 'district_id' => 3, 'name' => 'Monourom'],
            ['id' => 18, 'district_id' => 3, 'name' => 'Mittapheap'],
            ['id' => 19, 'district_id' => 3, 'name' => 'Veal Vong'],
            ['id' => 20, 'district_id' => 3, 'name' => 'Ou Russei Ti Mouy'],
            ['id' => 21, 'district_id' => 3, 'name' => 'Ou Russei Ti Pir'],
            ['id' => 22, 'district_id' => 3, 'name' => 'Ou Russei Ti Bei'],
            ['id' => 23, 'district_id' => 3, 'name' => 'Ou Russei Ti Buon'],
            ['id' => 24, 'district_id' => 4, 'name' => 'Phsar Depou Ti Muoy'],
            ['id' => 25, 'district_id' => 4, 'name' => 'Phsar Depou Ti Pir'],
            ['id' => 26, 'district_id' => 4, 'name' => 'Phsar Depou Ti Bei'],
            ['id' => 27, 'district_id' => 4, 'name' => 'Tuek Lak Ti Muoy'],
            ['id' => 28, 'district_id' => 4, 'name' => 'Tuek Lak Ti Pir'],
            ['id' => 29, 'district_id' => 4, 'name' => 'Tuek Lak Ti Bei'],
            ['id' => 30, 'district_id' => 4, 'name' => 'Boeng Kak Ti Muoy'],
            ['id' => 31, 'district_id' => 4, 'name' => 'Boeng Kak Ti Pir'],
            ['id' => 32, 'district_id' => 4, 'name' => 'Phsar Daeum Kor'],
            ['id' => 33, 'district_id' => 4, 'name' => 'Boeng Salang'],
            ['id' => 34, 'district_id' => 5, 'name' => 'Dangkao'],
            ['id' => 35, 'district_id' => 5, 'name' => 'Pong Tuek'],
            ['id' => 36, 'district_id' => 5, 'name' => 'Prey Veaeng'],
            ['id' => 37, 'district_id' => 5, 'name' => 'Prey Sa'],
            ['id' => 38, 'district_id' => 5, 'name' => 'Krang Pongro'],
            ['id' => 39, 'district_id' => 5, 'name' => 'Prateah Lang'],
            ['id' => 40, 'district_id' => 5, 'name' => 'Sak Sampov'],
            ['id' => 41, 'district_id' => 5, 'name' => 'Cheung Aek'],
            ['id' => 42, 'district_id' => 5, 'name' => 'Kong Noy'],
            ['id' => 43, 'district_id' => 5, 'name' => 'Preaek Kampues'],
            ['id' => 44, 'district_id' => 5, 'name' => 'Roluos'],
            ['id' => 45, 'district_id' => 5, 'name' => 'Spean Thma'],
            ['id' => 46, 'district_id' => 5, 'name' => 'Tien'],
            ['id' => 47, 'district_id' => 6, 'name' => 'Stueng Mean Chey'],
            ['id' => 48, 'district_id' => 6, 'name' => 'Boeng Tumpu'],
            ['id' => 49, 'district_id' => 6, 'name' => 'Chak Angrea Leu'],
            ['id' => 50, 'district_id' => 6, 'name' => 'Chak Angrea Kraom'],
            ['id' => 51, 'district_id' => 7, 'name' => 'Tuol Sangke'],
            ['id' => 52, 'district_id' => 7, 'name' => 'Svay Pak'],
            ['id' => 53, 'district_id' => 7, 'name' => 'Kimlomaetr Lekh Prammuoy'],
            ['id' => 54, 'district_id' => 7, 'name' => 'Ruessei Kaev'],
            ['id' => 55, 'district_id' => 7, 'name' => 'Chrang Chamreh Ti Muoy'],
            ['id' => 56, 'district_id' => 7, 'name' => 'Chrang Chamreh Ti Pir'],
            ['id' => 57, 'district_id' => 8, 'name' => 'Phnom Penh Thmei'],
            ['id' => 58, 'district_id' => 8, 'name' => 'Tuek Thla'],
            // ['id' => 58, 'district_id' => 8, 'name' => 'Khmuonh'],
            ['id' => 59, 'district_id' => 8, 'name' => 'Krang Thnong'],
            ['id' => 60, 'district_id' => 9, 'name' => 'Trapeang Krasang'],
            ['id' => 61, 'district_id' => 9, 'name' => 'Phleung Chheh Roteh'],
            ['id' => 62, 'district_id' => 9, 'name' => 'Choam Chau'],
            ['id' => 63, 'district_id' => 9, 'name' => 'Kakab'],
            ['id' => 64, 'district_id' => 9, 'name' => 'Samraong Kraom'],
            ['id' => 65, 'district_id' => 9, 'name' => 'Boeng Thum'],
            ['id' => 66, 'district_id' => 9, 'name' => 'Kamboul'],
            ['id' => 67, 'district_id' => 9, 'name' => 'Kantaok'],
            ['id' => 68, 'district_id' => 9, 'name' => 'Ovlaok'],
            ['id' => 69, 'district_id' => 9, 'name' => 'Snaor'],
            ['id' => 70, 'district_id' => 10, 'name' => 'Chrouy Changvar'],
            ['id' => 71, 'district_id' => 10, 'name' => 'Praek Lieb'],
            ['id' => 72, 'district_id' => 10, 'name' => 'Kaoh Dach'],
            ['id' => 73, 'district_id' => 10, 'name' => 'Bak Kaeng'],
            ['id' => 74, 'district_id' => 11, 'name' => 'Preaek Phnov'],
            ['id' => 75, 'district_id' => 11, 'name' => 'Ponhea Pon'],
            ['id' => 76, 'district_id' => 11, 'name' => 'Samraong'],
            ['id' => 77, 'district_id' => 11, 'name' => 'Kouk Roka'],
            ['id' => 78, 'district_id' => 11, 'name' => 'Ponsang'],
            ['id' => 79, 'district_id' => 12, 'name' => 'Chhbar Ampov Ti Muoy'],
            ['id' => 80, 'district_id' => 12, 'name' => 'Chbar Ampov Ti Pir'],
            ['id' => 81, 'district_id' => 12, 'name' => 'Nirouth'],
            ['id' => 82, 'district_id' => 12, 'name' => 'Preaek Pra'],
            ['id' => 83, 'district_id' => 12, 'name' => 'Veal Sbov'],
            ['id' => 84, 'district_id' => 12, 'name' => 'Preaek Aeng'],
            ['id' => 85, 'district_id' => 12, 'name' => 'Kbal Kaoh'],
            ['id' => 86, 'district_id' => 12, 'name' => 'Preaek Thmei'],
            ['id' => 87, 'district_id' => 13, 'name' => 'Banteay Neang'],
            ['id' => 88, 'district_id' => 13, 'name' => 'Chamnaom'],
            ['id' => 89, 'district_id' => 13, 'name' => 'Bat Trang'],
            ['id' => 90, 'district_id' => 13, 'name' => 'Kouk Ballangk'],
            ['id' => 91, 'district_id' => 13, 'name' => 'Phnum Touch'],
            ['id' => 92, 'district_id' => 13, 'name' => 'Ruessei Kraok'],
            ['id' => 93, 'district_id' => 14, 'name' => 'Poy Char'],
            ['id' => 94, 'district_id' => 14, 'name' => 'Phnum Dei'],
            ['id' => 95, 'district_id' => 14, 'name' => 'Spean Sraeng'],
            ['id' => 96, 'district_id' => 14, 'name' => 'Nam Tau'],
            ['id' => 97, 'district_id' => 14, 'name' => 'Ponley'],
            ['id' => 98, 'district_id' => 15, 'name' => 'Chnuor Mean Chey'],
            ['id' => 99, 'district_id' => 15, 'name' => 'Chob Vari'],
            ['id' => 100, 'district_id' => 15, 'name' => 'Phnum Lieb'],
            ['id' => 101, 'district_id' => 15, 'name' => 'Prasat'],
            ['id' => 102, 'district_id' => 15, 'name' => 'Preak Netr Preah'],
            ['id' => 103, 'district_id' => 16, 'name' => 'Changha'],
            ['id' => 104, 'district_id' => 16, 'name' => 'Koub'],
            ['id' => 105, 'district_id' => 16, 'name' => 'Kuttasat'],
            ['id' => 106, 'district_id' => 16, 'name' => 'Samraong'],
            ['id' => 107, 'district_id' => 17, 'name' => 'Kampong Svay'],
            ['id' => 108, 'district_id' => 17, 'name' => 'Kaoh Pong Satv'],
            ['id' => 109, 'district_id' => 17, 'name' => 'Mkak'],
            ['id' => 110, 'district_id' => 17, 'name' => 'Phniet'],
            ['id' => 111, 'district_id' => 17, 'name' => 'Preah Ponlea'],
            ['id' => 112, 'district_id' => 18, 'name' => 'Banteay Chhmar'],
            ['id' => 113, 'district_id' => 18, 'name' => 'Kouk Romiet'],
            ['id' => 114, 'district_id' => 18, 'name' => 'Phum Thmei'],
            ['id' => 115, 'district_id' => 18, 'name' => 'Thma Puok'],
            ['id' => 116, 'district_id' => 19, 'name' => 'Phkoam'],
            ['id' => 117, 'district_id' => 19, 'name' => 'Sarongk'],
            ['id' => 118, 'district_id' => 19, 'name' => 'Sla Kram'],
            ['id' => 119, 'district_id' => 19, 'name' => 'Svay Chek'],
            ['id' => 120, 'district_id' => 20, 'name' => 'Boeng Beng'],
            ['id' => 121, 'district_id' => 20, 'name' => 'Malai'],
            ['id' => 122, 'district_id' => 20, 'name' => 'Malai'],
            ['id' => 123, 'district_id' => 20, 'name' => 'Ou Sampoar'],
            ['id' => 124, 'district_id' => 21, 'name' => 'Nimitt'],
            ['id' => 125, 'district_id' => 21, 'name' => 'Paoy Paet'],
            ['id' => 126, 'district_id' => 21, 'name' => 'Phsar Kandal'],
            ['id' => 127, 'district_id' => 22, 'name' => 'Kantueu Muoy'],
            ['id' => 128, 'district_id' => 22, 'name' => 'Kantueu Pir'],
            ['id' => 129, 'district_id' => 22, 'name' => 'Bay Damram'],
            ['id' => 130, 'district_id' => 22, 'name' => 'Chheu Teal'],
            ['id' => 131, 'district_id' => 22, 'name' => 'Chaeng Mean Chey'],
            ['id' => 132, 'district_id' => 23, 'name' => 'Ta Pung'],
            ['id' => 133, 'district_id' => 23, 'name' => 'Ta Meun'],
            ['id' => 134, 'district_id' => 23, 'name' => 'Ou Ta Ki'],
            ['id' => 135, 'district_id' => 24, 'name' => 'Chrey'],
            ['id' => 136, 'district_id' => 25, 'name' => 'Tuol Ta Ek'],
            ['id' => 137, 'district_id' => 25, 'name' => 'Prek Preah Sdach'],
            ['id' => 138, 'district_id' => 25, 'name' => 'Rottanak'],
            ['id' => 139, 'district_id' => 25, 'name' => 'Chomkar Somraong'],
            ['id' => 140, 'district_id' => 26, 'name' => 'Bavel'],
            ['id' => 141, 'district_id' => 26, 'name' => 'Khnach Romeas'],
            ['id' => 142, 'district_id' => 26, 'name' => 'Lvea'],
            ['id' => 143, 'district_id' => 26, 'name' => 'Prey Khpos'],
            ['id' => 144, 'district_id' => 26, 'name' => 'Ampil Pram Daeum'],
            ['id' => 145, 'district_id' => 27, 'name' => 'Preaek Norint'],
            ['id' => 146, 'district_id' => 27, 'name' => 'Samraong Knong'],
            ['id' => 147, 'district_id' => 27, 'name' => 'Preaek Khpob'],
            ['id' => 148, 'district_id' => 27, 'name' => 'Preaek Luong'],
            ['id' => 149, 'district_id' => 28, 'name' => 'Moung'],
            ['id' => 150, 'district_id' => 30, 'name' => 'Khnor Dambang'],
            ['id' => 151, 'district_id' => 30, 'name' => 'Kouk Rovieng'],
            ['id' => 152, 'district_id' => 30, 'name' => 'Pdau Chum'],
            ['id' => 153, 'district_id' => 31, 'name' => 'Kampong Cham'],
            ['id' => 154, 'district_id' => 31, 'name' => 'Sambuor Meas'],
            ['id' => 155, 'district_id' => 31, 'name' => 'Veal Vong'],
            ['id' => 156, 'district_id' => 32, 'name' => 'Anhchanh Rung'],
            ['id' => 157, 'district_id' => 32, 'name' => 'Chhnok Tru'],
            ['id' => 158, 'district_id' => 32, 'name' => 'Chak'],
            ['id' => 159, 'district_id' => 32, 'name' => 'Khon Rang'],
            ['id' => 160, 'district_id' => 33, 'name' => 'Chol Sar'],
            ['id' => 161, 'district_id' => 33, 'name' => 'Kaoh Thkov'],
            ['id' => 162, 'district_id' => 33, 'name' => 'Kampong Ous'],
            ['id' => 163, 'district_id' => 34, 'name' => 'Phsar Chhnang'],
            ['id' => 164, 'district_id' => 34, 'name' => 'Kampong Chhnang'],
            ['id' => 165, 'district_id' => 34, 'name' => 'Ber'],
            ['id' => 166, 'district_id' => 34, 'name' => 'Khsam'],
            ['id' => 167, 'district_id' => 35, 'name' => 'Basedth'],
            ['id' => 168, 'district_id' => 35, 'name' => 'Kat Phluk'],
            ['id' => 169, 'district_id' => 35, 'name' => 'Nitean'],
            ['id' => 170, 'district_id' => 36, 'name' => 'Chbar Mon'],
            ['id' => 171, 'district_id' => 36, 'name' => 'Kandaol Dom'],
            ['id' => 172, 'district_id' => 36, 'name' => 'Rokar Thum'],
            ['id' => 173, 'district_id' => 37, 'name' => 'Angk Popel'],
            ['id' => 174, 'district_id' => 37, 'name' => 'Chongruk'],
            ['id' => 175, 'district_id' => 37, 'name' => 'Moha Ruessei'],
            ['id' => 176, 'district_id' => 38, 'name' => 'Bak Sna'],
            ['id' => 177, 'district_id' => 38, 'name' => 'Ballangk'],
            ['id' => 178, 'district_id' => 38, 'name' => 'Baray'],
            ['id' => 179, 'district_id' => 39, 'name' => 'Chey'],
            ['id' => 180, 'district_id' => 39, 'name' => 'Damrei Slab'],
            ['id' => 181, 'district_id' => 39, 'name' => 'Kampong Kou'],
            ['id' => 182, 'district_id' => 39, 'name' => 'Kampong Svay'],
            ['id' => 183, 'district_id' => 40, 'name' => 'Damrei Choan Khla'],
            ['id' => 184, 'district_id' => 40, 'name' => 'Kampong Thum'],
            ['id' => 185, 'district_id' => 40, 'name' => 'Kampong Roteh'],
            ['id' => 186, 'district_id' => 40, 'name' => 'Ou Kanthor'],
            ['id' => 187, 'district_id' => 41, 'name' => 'Angk Phnum Touch'],
            ['id' => 188, 'district_id' => 41, 'name' => 'Ankor Chey'],
            ['id' => 189, 'district_id' => 41, 'name' => 'Champei'],
            ['id' => 190, 'district_id' => 42, 'name' => 'Banteay Meas Khang Kaeut'],
            ['id' => 191, 'district_id' => 42, 'name' => 'Banteay Meas Khang lech'],
            ['id' => 192, 'district_id' => 42, 'name' => 'Prey Tonle'],
            ['id' => 193, 'district_id' => 43, 'name' => 'Baniev'],
            ['id' => 194, 'district_id' => 43, 'name' => 'Takaen'],
            ['id' => 195, 'district_id' => 43, 'name' => 'Boeng Nimol'],
            ['id' => 196, 'district_id' => 44, 'name' => 'Ampov Prey'],
            ['id' => 197, 'district_id' => 44, 'name' => 'Anlong Romiet'],
            ['id' => 198, 'district_id' => 44, 'name' => 'Barku'],
            ['id' => 199, 'district_id' => 45, 'name' => 'Banteay Daek'],
            ['id' => 200, 'district_id' => 45, 'name' => 'Chheu Teal'],
            ['id' => 201, 'district_id' => 45, 'name' => 'Dei Edth'],
            ['id' => 202, 'district_id' => 46, 'name' => 'Bak Dav'],
            ['id' => 203, 'district_id' => 46, 'name' => 'Chey Thum'],
            ['id' => 204, 'district_id' => 46, 'name' => 'Kampong Chamlang'],
            ['id' => 205, 'district_id' => 47, 'name' => 'Chheu Kmau'],
            ['id' => 206, 'district_id' => 47, 'name' => 'Chrouy Ta Kaev'],
            ['id' => 207, 'district_id' => 47, 'name' => 'Kampong Kong'],
            ['id' => 208, 'district_id' => 48, 'name' => 'Kampong Phnum'],
            ['id' => 209, 'district_id' => 48, 'name' => 'Kam Samnar'],
            ['id' => 210, 'district_id' => 48, 'name' => 'Khpob Ateav'],
            ['id' => 211, 'district_id' => 49, 'name' => 'Akreiy Ksatr'],
            ['id' => 212, 'district_id' => 49, 'name' => 'Barong'],
            ['id' => 213, 'district_id' => 49, 'name' => 'Boeng Krum'],
            ['id' => 214, 'district_id' => 50, 'name' => 'Andoung Tuek'],
            ['id' => 215, 'district_id' => 50, 'name' => 'Kandaol'],
            ['id' => 216, 'district_id' => 50, 'name' => 'Ta Noun'],
            ['id' => 217, 'district_id' => 51, 'name' => 'Kaoh Sdach'],
            ['id' => 218, 'district_id' => 51, 'name' => 'Phnhi Meas'],
            ['id' => 219, 'district_id' => 51, 'name' => 'Preaek Khsach'],
            ['id' => 220, 'district_id' => 52, 'name' => 'Chrouy Pras'],
            ['id' => 221, 'district_id' => 52, 'name' => 'Kaoh Kapi'],
            ['id' => 222, 'district_id' => 52, 'name' => 'Ta Tai Kraom'],
            ['id' => 223, 'district_id' => 53, 'name' => 'Smach Mean Chey'],
            ['id' => 224, 'district_id' => 53, 'name' => 'Dang Tong'],
            ['id' => 225, 'district_id' => 53, 'name' => 'Stueng Veaeng'],
            ['id' => 226, 'district_id' => 54, 'name' => 'Angkaol'],
            ['id' => 227, 'district_id' => 54, 'name' => 'Pong Tuek'],
            ['id' => 228, 'district_id' => 54, 'name' => 'Kaeb'],
            ['id' => 229, 'district_id' => 55, 'name' => 'Prey Thum'],
            ['id' => 230, 'district_id' => 55, 'name' => 'Ou Krasar'],
            ['id' => 231, 'district_id' => 56, 'name' => 'Chong Phlah'],
            // ['id' => 231, 'district_id' => 56, 'name' => 'Memang'],
            ['id' => 232, 'district_id' => 56, 'name' => 'Srae Chhuk'],
            ['id' => 233, 'district_id' => 57, 'name' => 'Nang Khi Lik'],
            ['id' => 234, 'district_id' => 57, 'name' => 'A Buon Leu'],
            ['id' => 235, 'district_id' => 57, 'name' => 'Roya'],
            ['id' => 236, 'district_id' => 58, 'name' => 'Dak Dam'],
            ['id' => 237, 'district_id' => 58, 'name' => 'Saen Monourom'],
            ['id' => 238, 'district_id' => 58, 'name' => 'Krang Teh'],
            ['id' => 239, 'district_id' => 59, 'name' => 'Monourom'],
            ['id' => 240, 'district_id' => 59, 'name' => 'Sokh Dom'],
            ['id' => 241, 'district_id' => 59, 'name' => 'Spean Mean Chey'],
            ['id' => 242, 'district_id' => 60, 'name' => 'Anlong Veaeng'],
            ['id' => 243, 'district_id' => 60, 'name' => 'Trapeang Tav'],
            ['id' => 244, 'district_id' => 60, 'name' => 'Trapeang Prei'],
            ['id' => 245, 'district_id' => 61, 'name' => 'Ampil'],
            ['id' => 246, 'district_id' => 61, 'name' => 'Beng'],
            ['id' => 247, 'district_id' => 61, 'name' => 'Kouk Khpos'],
            ['id' => 248, 'district_id' => 62, 'name' => 'Cheung Tien'],
            ['id' => 249, 'district_id' => 62, 'name' => 'Chong Kal'],
            ['id' => 250, 'district_id' => 62, 'name' => 'Krasang'],
            ['id' => 251, 'district_id' => 64, 'name' => 'Bansay Reak'],
            ['id' => 252, 'district_id' => 64, 'name' => 'Bos Sbov'],
            ['id' => 253, 'district_id' => 64, 'name' => 'Koun Kriel'],
            ['id' => 254, 'district_id' => 65, 'name' => 'Pailin'],
            ['id' => 255, 'district_id' => 65, 'name' => 'Ou Ta Vau'],
            ['id' => 256, 'district_id' => 66, 'name' => 'Sala Krau'],
            ['id' => 257, 'district_id' => 66, 'name' => 'Stueng Trang'],
            ['id' => 258, 'district_id' => 67, 'name' => 'Kaoh Rung'],
            ['id' => 259, 'district_id' => 67, 'name' => 'Andoung Thma'],
            ['id' => 260, 'district_id' => 67, 'name' => 'Boeng Ta Prum'],
            ['id' => 261, 'district_id' => 68, 'name' => 'lek Muoy'],
            ['id' => 262, 'district_id' => 68, 'name' => 'Pir'],
            ['id' => 263, 'district_id' => 69, 'name' => 'Kampenh'],
            ['id' => 264, 'district_id' => 69, 'name' => 'Ou Treh'],
            ['id' => 265, 'district_id' => 70, 'name' => 'Chamkar Luong'],
            // ['id' => 265, 'district_id' => 70, 'name' => 'Kampong Seila'],
            ['id' => 266, 'district_id' => 71, 'name' => 'Sang'],
            ['id' => 267, 'district_id' => 71, 'name' => 'Tasu'],
            ['id' => 268, 'district_id' => 72, 'name' => 'Chhaeb Muoy'],
            ['id' => 269, 'district_id' => 72, 'name' => 'Chhaeb Pir'],
            ['id' => 270, 'district_id' => 72, 'name' => 'Sangkae Muoy'],
            ['id' => 271, 'district_id' => 73, 'name' => 'Choam Ksant'],
            ['id' => 272, 'district_id' => 73, 'name' => 'Tuek Kraham'],
            ['id' => 273, 'district_id' => 73, 'name' => 'Pring Thum'],
            ['id' => 274, 'district_id' => 74, 'name' => 'Kuleaen Tboung'],
            ['id' => 275, 'district_id' => 74, 'name' => 'Kuleaen Cheung'],
            ['id' => 276, 'district_id' => 75, 'name' => 'Kampong Pranak'],
            ['id' => 277, 'district_id' => 75, 'name' => 'Pal Hal'],
            ['id' => 278, 'district_id' => 77, 'name' => 'Boeng Bat Kandaol'],
            ['id' => 279, 'district_id' => 77, 'name' => 'Boeng Khnar'],
            ['id' => 280, 'district_id' => 78, 'name' => 'Anlong Vil'],
            ['id' => 281, 'district_id' => 78, 'name' => 'Kandieng'],
            ['id' => 282, 'district_id' => 79, 'name' => 'Anlong Tnaot'],
            ['id' => 283, 'district_id' => 79, 'name' => 'Ansa Chambak'],
            ['id' => 284, 'district_id' => 80, 'name' => 'Bak Chenhchien'],
            ['id' => 285, 'district_id' => 80, 'name' => 'Leach'],
            ['id' => 286, 'district_id' => 80, 'name' => 'Prongil'],
            ['id' => 287, 'district_id' => 81, 'name' => 'Chamraeun Phal'],
            ['id' => 288, 'district_id' => 81, 'name' => 'Lolok Sa'],
            ['id' => 289, 'district_id' => 82, 'name' => 'Ou Saom'],
            ['id' => 290, 'district_id' => 82, 'name' => 'Krapeu Pir'],
            ['id' => 291, 'district_id' => 82, 'name' => 'Anlong Reab'],
            ['id' => 292, 'district_id' => 82, 'name' => 'Thma Da'],
            ['id' => 293, 'district_id' => 83, 'name' => 'Boeng Preah'],
            ['id' => 294, 'district_id' => 83, 'name' => 'Cheung Phnum'],
            ['id' => 295, 'district_id' => 84, 'name' => 'Cheach'],
            ['id' => 296, 'district_id' => 84, 'name' => 'Doun Koeng'],
            ['id' => 297, 'district_id' => 85, 'name' => 'Ansaong'],
            ['id' => 298, 'district_id' => 85, 'name' => 'Cham'],
            ['id' => 299, 'district_id' => 86, 'name' => 'Chong Ampil'],
            ['id' => 300, 'district_id' => 86, 'name' => 'Kanhchriech'],
            ['id' => 301, 'district_id' => 87, 'name' => 'Angkor Sar'],
            ['id' => 302, 'district_id' => 87, 'name' => 'Chres'],
            ['id' => 304, 'district_id' => 88, 'name' => 'Angkor Angk'],
            ['id' => 305, 'district_id' => 88, 'name' => 'Kampong Prasat'],
            ['id' => 306, 'district_id' => 89, 'name' => 'Malik'],
            ['id' => 307, 'district_id' => 89, 'name' => 'Nhang'],
            ['id' => 308, 'district_id' => 90, 'name' => 'Kachanh'],
            ['id' => 309, 'district_id' => 90, 'name' => 'Labansiek'],
            ['id' => 310, 'district_id' => 91, 'name' => 'Kak'],
            ['id' => 311, 'district_id' => 91, 'name' => 'Keh Chong'],
            ['id' => 312, 'district_id' => 92, 'name' => 'Serei Mongkol'],
            ['id' => 313, 'district_id' => 92, 'name' => 'Srae Angkrorng'],
            ['id' => 314, 'district_id' => 93, 'name' => 'Char Chhuk'],
            ['id' => 315, 'district_id' => 93, 'name' => 'Doun Peng'],
            ['id' => 316, 'district_id' => 94, 'name' => 'Chob Ta Trav'],
            ['id' => 317, 'district_id' => 94, 'name' => 'Leang Dai'],
            ['id' => 318, 'district_id' => 95, 'name' => 'Khnar Sanday'],
            ['id' => 319, 'district_id' => 95, 'name' => 'Khun Ream'],
            ['id' => 320, 'district_id' => 96, 'name' => 'Anlong Samnar'],
            ['id' => 321, 'district_id' => 96, 'name' => 'Chi Kraeng'],
            ['id' => 322, 'district_id' => 97, 'name' => 'Chanleas Dai'],
            ['id' => 323, 'district_id' => 97, 'name' => 'Kampong Thkov'],
            ['id' => 324, 'district_id' => 98, 'name' => 'Kamphun'],
            ['id' => 325, 'district_id' => 98, 'name' => 'Kbal Romeas'],
            // ['id' => 325, 'district_id' => 99, 'name' => 'Kaoh Preah'],
            ['id' => 326, 'district_id' => 99, 'name' => 'Kaoh Sampeay'],
            ['id' => 327, 'district_id' => 100, 'name' => 'Preaek Meas'],
            ['id' => 328, 'district_id' => 100, 'name' => 'Sekong'],
            ['id' => 329, 'district_id' => 101, 'name' => 'Stueng Traeng'],
            ['id' => 330, 'district_id' => 101, 'name' => 'Srah Ruessei'],
            ['id' => 331, 'district_id' => 102, 'name' => 'Chantrea'],
            ['id' => 332, 'district_id' => 102, 'name' => 'Chres'],
            ['id' => 333, 'district_id' => 103, 'name' => 'Banteay Krang'],
            ['id' => 334, 'district_id' => 103, 'name' => 'Nhor'],
            ['id' => 335, 'district_id' => 104, 'name' => 'Bos Mon'],
            ['id' => 336, 'district_id' => 104, 'name' => 'Thmea'],
            // ['id' => 336, 'district_id' => 105, 'name' => 'Ampil'],
            ['id' => 337, 'district_id' => 105, 'name' => 'Andoung Pou'],
            ['id' => 338, 'district_id' => 106, 'name' => 'Angkor Borei'],
            // ['id' => 338, 'district_id' => 106, 'name' => 'Ba Srae'],
            ['id' => 340, 'district_id' => 107, 'name' => 'Chambak'],
            ['id' => 341, 'district_id' => 107, 'name' => 'Champei'],
            ['id' => 342, 'district_id' => 108, 'name' => 'Borei Cholsar'],
            ['id' => 343, 'district_id' => 108, 'name' => 'Chey Chouk'],
            ['id' => 344, 'district_id' => 109, 'name' => 'Angk Prasat'],
            ['id' => 345, 'district_id' => 109, 'name' => 'Preah Bat Choan Chum'],
            ['id' => 346, 'district_id' => 110, 'name' => 'Chong Cheach'],
            ['id' => 347, 'district_id' => 110, 'name' => 'Dambae'],
            ['id' => 348, 'district_id' => 111, 'name' => 'Chhuk'],
            ['id' => 349, 'district_id' => 111, 'name' => 'Chumnik'],
            ['id' => 350, 'district_id' => 112, 'name' => 'Chan Mul'],
            ['id' => 351, 'district_id' => 112, 'name' => 'Choam'],
            ['id' => 352, 'district_id' => 113, 'name' => 'Ampil Ta Pok'],
            ['id' => 353, 'district_id' => 113, 'name' => 'Chak'],
        ];
        foreach ($communes as $commune) {
            Commune::create($commune);
        }
    }
}
