<?php

namespace Database\Seeders;

use App\Models\District;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DistrictSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $districts = [
            ['id' => 1, 'province_id' => 1, 'name' => 'Chamkar Mon'],
            ['id' => 2, 'province_id' => 1, 'name' => 'Doun Penh'],
            ['id' => 3, 'province_id' => 1, 'name' => 'Prampir Meakkakra'],
            ['id' => 4, 'province_id' => 1, 'name' => 'Toul Kok'],
            ['id' => 5, 'province_id' => 1, 'name' => 'Dang Kao'],
            ['id' => 6, 'province_id' => 1, 'name' => 'Mean Chey'],
            ['id' => 7, 'province_id' => 1, 'name' => 'Russey Keo'],
            ['id' => 8, 'province_id' => 1, 'name' => 'Sen Sok'],
            ['id' => 9, 'province_id' => 1, 'name' => 'Por Senchey'],
            ['id' => 10, 'province_id' => 1, 'name' => 'Chroy Chongvar'],
            ['id' => 11, 'province_id' => 1, 'name' => 'Prek Pnov'],
            ['id' => 12, 'province_id' => 1, 'name' => 'Chbar Ampov'],
            ['id' => 13, 'province_id' => 2, 'name' => 'Mongkol Borei'],
            ['id' => 14, 'province_id' => 2, 'name' => 'Phnum Srok'],
            ['id' => 15, 'province_id' => 2, 'name' => 'Preah Netr Preah'],
            ['id' => 16, 'province_id' => 2, 'name' => 'Ou Chrov'],
            ['id' => 17, 'province_id' => 2, 'name' => 'Serei Saophoan'],
            ['id' => 18, 'province_id' => 2, 'name' => 'Thma Pouk'],
            ['id' => 19, 'province_id' => 2, 'name' => 'Svay Chek'],
            ['id' => 20, 'province_id' => 2, 'name' => 'Malai'],
            ['id' => 21, 'province_id' => 2, 'name' => 'Paoy Paet'],
            ['id' => 22, 'province_id' => 3, 'name' => 'Banan'],
            ['id' => 23, 'province_id' => 3, 'name' => 'Thma Koul'],
            ['id' => 24, 'province_id' => 3, 'name' => 'Battambang'],
            ['id' => 25, 'province_id' => 3, 'name' => 'Bavel'],
            ['id' => 26, 'province_id' => 3, 'name' => 'Aek Phnum'],
            ['id' => 27, 'province_id' => 3, 'name' => 'Moung Ruessei'],
            ['id' => 28, 'province_id' => 4, 'name' => 'Batheay'],
            ['id' => 29, 'province_id' => 4, 'name' => 'Chamkar Leu'],
            ['id' => 30, 'province_id' => 4, 'name' => 'Cheung Prey'],
            ['id' => 31, 'province_id' => 4, 'name' => 'Kampong Cham'],
            ['id' => 32, 'province_id' => 5, 'name' => 'Baribour'],
            ['id' => 33, 'province_id' => 5, 'name' => 'Chol Kiri'],
            ['id' => 34, 'province_id' => 5, 'name' => 'Kampong Chhnang'],
            ['id' => 35, 'province_id' => 6, 'name' => 'Basedth'],
            ['id' => 36, 'province_id' => 6, 'name' => 'Chbar Mon'],
            ['id' => 37, 'province_id' => 6, 'name' => 'Kong Pisei'],
            ['id' => 38, 'province_id' => 7, 'name' => 'Baray'],
            ['id' => 39, 'province_id' => 7, 'name' => 'Kampong Svay'],
            ['id' => 40, 'province_id' => 7, 'name' => 'Stueng Saen'],
            ['id' => 41, 'province_id' => 8, 'name' => 'Angkor Chey'],
            ['id' => 42, 'province_id' => 8, 'name' => 'Banteay Meas'],
            ['id' => 43, 'province_id' => 8, 'name' => 'Chhuk'],
            ['id' => 44, 'province_id' => 8, 'name' => 'Chum Kiri'],
            ['id' => 45, 'province_id' => 9, 'name' => 'Kandal Stueng'],
            ['id' => 46, 'province_id' => 9, 'name' => 'Kien Svay'],
            ['id' => 47, 'province_id' => 9, 'name' => 'Khsach Kandal'],
            ['id' => 48, 'province_id' => 9, 'name' => 'Kaoh Thum'],
            ['id' => 49, 'province_id' => 9, 'name' => 'Leuk Daek'],
            ['id' => 50, 'province_id' => 10, 'name' => 'Botum Sakor'],
            ['id' => 51, 'province_id' => 10, 'name' => 'Kiri Sakor'],
            ['id' => 51, 'province_id' => 10, 'name' => 'Kaoh Kong'],
            ['id' => 52, 'province_id' => 10, 'name' => 'Khemara Phoumin'],
            ['id' => 53, 'province_id' => 11, 'name' => 'Damnak Changaeur'],
            ['id' => 54, 'province_id' => 11, 'name' => 'Kaeb'],
            ['id' => 55, 'province_id' => 12, 'name' => 'Kaev Seima'],
            ['id' => 56, 'province_id' => 12, 'name' => 'Kaoh Nheaek'],
            ['id' => 57, 'province_id' => 12, 'name' => 'Ou Reang'],
            ['id' => 58, 'province_id' => 12, 'name' => 'Pech Chreada'],
            ['id' => 59, 'province_id' => 12, 'name' => 'Saen Monourom'],
            // ['id' => 60, 'province_id' => 12, 'name' => 'Chetr Borei'],
            ['id' => 61, 'province_id' => 13, 'name' => 'Chhloung'],
            ['id' => 62, 'province_id' => 13, 'name' => 'Kracheh'],
            ['id' => 63, 'province_id' => 13, 'name' => 'Prek Prasab'],
            ['id' => 64, 'province_id' => 13, 'name' => 'Sambour'],
            ['id' => 65, 'province_id' => 14, 'name' => 'Banteay Ampil'],
            ['id' => 66, 'province_id' => 14, 'name' => 'Chong Kal'],
            ['id' => 67, 'province_id' => 14, 'name' => 'Samraong'],
            ['id' => 68, 'province_id' => 14, 'name' => 'Trapeang Prasat'],
            ['id' => 69, 'province_id' => 15, 'name' => 'Pailin'],
            ['id' => 70, 'province_id' => 15, 'name' => 'Sala Krau'],
            ['id' => 75,  'province_id' => 16, 'name' => 'Chey Saen'],
            ['id' => 76, 'province_id' => 16, 'name' => 'Chhaeb'],
            ['id' => 77, 'province_id' => 16, 'name' => 'Choam Ksant'],
            ['id' => 78, 'province_id' => 16, 'name' => 'Kuleaen'],
            ['id' => 79, 'province_id' => 16, 'name' => 'Preah Vihear'],
            ['id' => 80, 'province_id' => 17, 'name' => 'Bakan'],
            ['id' => 81, 'province_id' => 17, 'name' => 'Kandieng'],
            ['id' => 82, 'province_id' => 17, 'name' => 'Krakor'],
            ['id' => 83, 'province_id' => 17, 'name' => 'Phnum Kravanh'],
            ['id' => 84, 'province_id' => 17, 'name' => 'Pursat'],
            ['id' => 85, 'province_id' => 17, 'name' => 'Veal Veaeng'],
            ['id' => 86, 'province_id' => 18, 'name' => 'Ba Phnum'],
            ['id' => 87, 'province_id' => 18, 'name' => 'Kamchay Mear'],
            ['id' => 88, 'province_id' => 18, 'name' => 'Kampong Trabaek'],
            ['id' => 89, 'province_id' => 18, 'name' => 'Kanhchriech'],
            ['id' => 90, 'province_id' => 18, 'name' => 'Me Sang'],
            ['id' => 91, 'province_id' => 18, 'name' => 'Peam Chor'],
            ['id' => 92, 'province_id' => 19, 'name' => 'Andoung Meas'],
            ['id' => 93, 'province_id' => 19, 'name' => 'Ban Lung'],
            ['id' => 95, 'province_id' => 19, 'name' => 'Bar Kaev'],
            ['id' => 96, 'province_id' => 19, 'name' => 'Koun Mom'],
            ['id' => 97, 'province_id' => 20, 'name' => 'Angkor Chum'],
            ['id' => 98, 'province_id' => 20, 'name' => 'Angkor Thum'],
            ['id' => 99, 'province_id' => 20, 'name' => 'Banteay Srei'],
            ['id' => 100, 'province_id' => 20, 'name' => 'Chi Kraeng'],
            ['id' => 101, 'province_id' => 20, 'name' => 'Kralanh'],
            ['id' => 102, 'province_id' => 21, 'name' => 'Sesan'],
            ['id' => 103, 'province_id' => 21, 'name' => 'Siem Bouk'],
            ['id' => 104, 'province_id' => 21, 'name' => 'Siem Pang'],
            ['id' => 105, 'province_id' => 21, 'name' => 'Stueng Traeng'],
            ['id' => 106, 'province_id' => 22, 'name' => 'Chantrea'],
            ['id' => 107, 'province_id' => 22, 'name' => 'Kampong Rou'],
            ['id' => 108, 'province_id' => 22, 'name' => 'Rumduol'],
            ['id' => 109, 'province_id' => 22, 'name' => 'Romeas Haek'],
            ['id' => 110, 'province_id' => 23, 'name' => 'Angkor Borei'],
            ['id' => 111, 'province_id' => 23, 'name' => 'Bati'],
            ['id' => 112, 'province_id' => 23, 'name' => 'Borei Cholsar'],
            ['id' => 113, 'province_id' => 23, 'name' => 'Kiri Vong'],
            ['id' => 114, 'province_id' => 24, 'name' => 'Dambae'],
            ['id' => 115, 'province_id' => 24, 'name' => 'Krouch Chhmar'],
            ['id' => 116, 'province_id' => 24, 'name' => 'Memot'],
            ['id' => 117, 'province_id' => 24, 'name' => 'Ou Reang Ov'],

        ];
        foreach ($districts as $district) {
            District::create($district);
        }
    }
}
