<?php

namespace Database\Seeders;

use App\Models\District;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DistrictSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $districts = [
            ['id' => 1, 'province_id' => 1, 'name' => 'Chamkar Mon'],
            ['id' => 2, 'province_id' => 1, 'name' => 'Doun Penh'],
            ['id' => 3, 'province_id' => 1, 'name' => 'Prampir Meakkakra'],
            ['id' => 4, 'province_id' => 1, 'name' => 'Toul Kok'],
            ['id' => 5, 'province_id' => 1, 'name' => 'Dang Kao'],
            ['id' => 6, 'province_id' => 1, 'name' => 'Mean Chey'],
            ['id' => 7, 'province_id' => 1, 'name' => 'Russey Keo'],
            ['id' => 8, 'province_id' => 1, 'name' => 'Sen Sok'],
            ['id' => 9, 'province_id' => 1, 'name' => 'Por Senchey'],
            ['id' => 10, 'province_id' => 1, 'name' => 'Chroy Chongvar'],
            ['id' => 11, 'province_id' => 1, 'name' => 'Prek Pnov'],
            ['id' => 12, 'province_id' => 1, 'name' => 'Chbar Ampov'],
            ['id' => 13, 'province_id' => 2, 'name' => 'Mongkol Borei'],
            ['id' => 14, 'province_id' => 2, 'name' => 'Phnum Srok'],
            ['id' => 15, 'province_id' => 2, 'name' => 'Preah Netr Preah'],
            ['id' => 16, 'province_id' => 2, 'name' => 'Ou Chrov'],
            ['id' => 17, 'province_id' => 2, 'name' => 'Serei Saophoan'],
            ['id' => 18, 'province_id' => 2, 'name' => 'Thma Pouk'],
            ['id' => 19, 'province_id' => 2, 'name' => 'Svay Chek'],
            ['id' => 20, 'province_id' => 2, 'name' => 'Malai'],
            ['id' => 21, 'province_id' => 2, 'name' => 'Paoy Paet'],
            ['id' => 22, 'province_id' => 3, 'name' => 'Banan'],
            ['id' => 23, 'province_id' => 3, 'name' => 'Thma Koul'],
            ['id' => 24, 'province_id' => 3, 'name' => 'Battambang'],
            ['id' => 25, 'province_id' => 3, 'name' => 'Bavel'],
            ['id' => 26, 'province_id' => 3, 'name' => 'Aek Phnum'],
            ['id' => 27, 'province_id' => 3, 'name' => 'Moung Ruessei'],
            ['id' => 28, 'province_id' => 3, 'name' => 'Rotonak Mondol'],
            ['id' => 29, 'province_id' => 3, 'name' => 'Sangkae'],
            ['id' => 30, 'province_id' => 3, 'name' => 'Samlout'],
            ['id' => 31, 'province_id' => 3, 'name' => 'Sampov Lun'],
            ['id' => 32, 'province_id' => 3, 'name' => 'Phnum Proek'],
            ['id' => 33, 'province_id' => 3, 'name' => 'Kamrieng'],
            ['id' => 34, 'province_id' => 3, 'name' => 'Koas Krala'],
            ['id' => 35, 'province_id' => 3, 'name' => 'Rukh Kiri'],
            ['id' => 36, 'province_id' => 4, 'name' => 'Batheay'],
            ['id' => 37, 'province_id' => 4, 'name' => 'Chamkar Leu'],
            ['id' => 38, 'province_id' => 4, 'name' => 'Cheung Prey'],
            ['id' => 39, 'province_id' => 4, 'name' => 'Kampong Cham'],
            ['id' => 40, 'province_id' => 4, 'name' => 'Kampong Siem'],
            ['id' => 41, 'province_id' => 4, 'name' => 'Kang Meas'],
            ['id' => 42, 'province_id' => 4, 'name' => 'Kaoh Soutin'],
            ['id' => 43, 'province_id' => 4, 'name' => 'Prey Chhor'],
            ['id' => 44, 'province_id' => 4, 'name' => 'Srei Santhor'],
            ['id' => 45, 'province_id' => 4, 'name' => 'Stueng Trang'],
            ['id' => 46, 'province_id' => 5, 'name' => 'Baribour'],
            ['id' => 47, 'province_id' => 5, 'name' => 'Chol Kiri'],
            ['id' => 48, 'province_id' => 5, 'name' => 'Kampong Chhnang'],
            ['id' => 49, 'province_id' => 5, 'name' => 'Kampong Leaeng'],
            ['id' => 50, 'province_id' => 5, 'name' => 'Kampong Tralach'],
            ['id' => 51, 'province_id' => 5, 'name' => 'Rolea Bier'],
            ['id' => 52, 'province_id' => 5, 'name' => 'Sameakki Mean Chey'],
            ['id' => 53, 'province_id' => 5, 'name' => 'Tuek Phos'],
            ['id' => 54, 'province_id' => 6, 'name' => 'Basedth'],
            ['id' => 55, 'province_id' => 6, 'name' => 'Chbar Mon'],
            ['id' => 56, 'province_id' => 6, 'name' => 'Kong Pisei'],
            ['id' => 57, 'province_id' => 6, 'name' => 'Aoral'],
            ['id' => 58, 'province_id' => 6, 'name' => 'Odongk'],
            ['id' => 59, 'province_id' => 6, 'name' => 'Phnum Sruoch'],
            ['id' => 60, 'province_id' => 6, 'name' => 'Samraong Tong'],
            ['id' => 61, 'province_id' => 6, 'name' => 'Thpong'],
            ['id' => 62, 'province_id' => 7, 'name' => 'Baray'],
            ['id' => 63, 'province_id' => 7, 'name' => 'Kampong Svay'],
            ['id' => 64, 'province_id' => 7, 'name' => 'Stueng Saen'],
            ['id' => 65, 'province_id' => 7, 'name' => 'Prasat Ballangk'],
            ['id' => 66, 'province_id' => 7, 'name' => 'Prasat Sambour'],
            ['id' => 67, 'province_id' => 7, 'name' => 'Sandan'],
            ['id' => 68, 'province_id' => 7, 'name' => 'Santuk'],
            ['id' => 69, 'province_id' => 7, 'name' => 'Stoung'],
            ['id' => 70, 'province_id' => 8, 'name' => 'Angkor Chey'],
            ['id' => 71, 'province_id' => 8, 'name' => 'Banteay Meas'],
            ['id' => 72, 'province_id' => 8, 'name' => 'Chhuk'],
            ['id' => 73, 'province_id' => 8, 'name' => 'Chum Kiri'],
            ['id' => 74, 'province_id' => 8, 'name' => 'Dang Tong'],
            ['id' => 75, 'province_id' => 8, 'name' => 'Kampong Trach'],
            ['id' => 76, 'province_id' => 8, 'name' => 'Tuek Chhou'],
            ['id' => 77, 'province_id' => 8, 'name' => 'Kampot'],
            ['id' => 78, 'province_id' => 9, 'name' => 'Kandal Stueng'],
            ['id' => 79, 'province_id' => 9, 'name' => 'Kien Svay'],
            ['id' => 80, 'province_id' => 9, 'name' => 'Khsach Kandal'],
            ['id' => 81, 'province_id' => 9, 'name' => 'Kaoh Thum'],
            ['id' => 82, 'province_id' => 9, 'name' => 'Leuk Daek'],
            ['id' => 83, 'province_id' => 9, 'name' => 'Lvea Aem'],
            ['id' => 84, 'province_id' => 9, 'name' => 'Mukh Kampul'],
            ['id' => 85, 'province_id' => 9, 'name' => 'Angk Snuol'],
            ['id' => 86, 'province_id' => 9, 'name' => 'Ponhea Lueu'],
            ['id' => 87, 'province_id' => 9, 'name' => 'Sang'],
            ['id' => 88, 'province_id' => 9, 'name' => 'Ta Khmau'],
            ['id' => 89, 'province_id' => 10, 'name' => 'Botum Sakor'],
            ['id' => 90, 'province_id' => 10, 'name' => 'Kiri Sakor'],
            ['id' => 91, 'province_id' => 10, 'name' => 'Kaoh Kong'],
            ['id' => 92, 'province_id' => 10, 'name' => 'Khemara Phoumin'],
            ['id' => 93, 'province_id' => 10, 'name' => 'Mondol Seima'],
            ['id' => 94, 'province_id' => 10, 'name' => 'Srae Ambel'],
            ['id' => 95, 'province_id' => 10, 'name' => 'Thma Bang'],
            ['id' => 96, 'province_id' => 11, 'name' => 'Damnak Changaeur'],
            ['id' => 97, 'province_id' => 11, 'name' => 'Kaeb'],
            ['id' => 98, 'province_id' => 12, 'name' => 'Chhloung'],
            ['id' => 99, 'province_id' => 12, 'name' => 'Kracheh'],
            ['id' => 100, 'province_id' => 12, 'name' => 'Prek Prasab'],
            ['id' => 101, 'province_id' => 12, 'name' => 'Sambour'],
            ['id' => 102, 'province_id' => 12, 'name' => 'Snuol'],
            ['id' => 103, 'province_id' => 12, 'name' => 'Chetr Borei'],
            ['id' => 104, 'province_id' => 13, 'name' => 'Chhloung'],
            ['id' => 105, 'province_id' => 13, 'name' => 'Kracheh'],
            ['id' => 106, 'province_id' => 13, 'name' => 'Prek Prasab'],
            ['id' => 107, 'province_id' => 13, 'name' => 'Sambour'],
            ['id' => 108, 'province_id' => 13, 'name' => 'Snuol'],
            ['id' => 109, 'province_id' => 13, 'name' => 'Anlong Veaeng'],
            ['id' => 1100, 'province_id' => 14, 'name' => 'Banteay Ampil'],
            ['id' => 111, 'province_id' => 14, 'name' => 'Chong Kal'],
            ['id' => 112, 'province_id' => 14, 'name' => 'Samraong'],
            ['id' => 113, 'province_id' => 14, 'name' => 'Trapeang Prasat'],
            ['id' => 114, 'province_id' => 15, 'name' => 'Pailin'],
            ['id' => 115, 'province_id' => 15, 'name' => 'Sala Krau'],
            ['id' => 116, 'province_id' => 16, 'name' => 'Preah Sihanouk'],
            ['id' => 117, 'province_id' => 16, 'name' => 'Prey Nob'],
            ['id' => 118, 'province_id' => 16, 'name' => 'Stueng Hav'],
            ['id' => 119, 'province_id' => 16, 'name' => 'Kampong Seila'],
            ['id' => 120, 'province_id' => 17, 'name' => 'Chey Saen'],
            ['id' => 121, 'province_id' => 17, 'name' => 'Chhaeb'],
            ['id' => 122, 'province_id' => 17, 'name' => 'Choam Ksant'],
            ['id' => 123, 'province_id' => 17, 'name' => 'Kuleaen'],
            ['id' => 124, 'province_id' => 17, 'name' => 'Rovieng'],
            ['id' => 125, 'province_id' => 17, 'name' => 'Sangkum Thmei'],
            ['id' => 126, 'province_id' => 17, 'name' => 'Tbaeng Mean Chey'],
            ['id' => 127, 'province_id' => 17, 'name' => 'Preah Vihear'],
            ['id' => 128, 'province_id' => 18, 'name' => 'Bakan'],
            ['id' => 129, 'province_id' => 18, 'name' => 'Kandieng'],
            ['id' => 130, 'province_id' => 18, 'name' => 'Krakor'],
            ['id' => 131, 'province_id' => 18, 'name' => 'Phnum Kravanh'],
            ['id' => 132, 'province_id' => 18, 'name' => 'Pursat'],
            ['id' => 133, 'province_id' => 18, 'name' => 'Veal Veaeng'],
            ['id' => 134, 'province_id' => 19, 'name' => 'Ba Phnum'],
            ['id' => 135, 'province_id' => 19, 'name' => 'Kamchay Mear'],
            ['id' => 136, 'province_id' => 19, 'name' => 'Kampong Trabaek'],
            ['id' => 137, 'province_id' => 19, 'name' => 'Kanhchriech'],
            ['id' => 138, 'province_id' => 19, 'name' => 'Me Sang'],
            ['id' => 139, 'province_id' => 19, 'name' => 'Peam Chor'],
            ['id' => 140, 'province_id' => 19, 'name' => 'Peam Ro'],
            ['id' => 141, 'province_id' => 19, 'name' => 'Pea Reang'],
            ['id' => 142, 'province_id' => 19, 'name' => 'Preah Sdach'],
            ['id' => 143, 'province_id' => 19, 'name' => 'Prey Veng'],
            ['id' => 144, 'province_id' => 19, 'name' => 'Pur Rieng'],
            ['id' => 145, 'province_id' => 19, 'name' => 'Sithor Kandal'],
            ['id' => 146, 'province_id' => 19, 'name' => 'Svay Antor'],
            ['id' => 147, 'province_id' => 20, 'name' => 'Andoung Meas'],
            ['id' => 148, 'province_id' => 20, 'name' => 'Ban Lung'],
            ['id' => 149, 'province_id' => 20, 'name' => 'Bar Kaev'],
            ['id' => 150, 'province_id' => 20, 'name' => 'Koun Mom'],
            ['id' => 151, 'province_id' => 20, 'name' => 'Lumphat'],
            ['id' => 152, 'province_id' => 20, 'name' => 'Ou Chum'],
            ['id' => 153, 'province_id' => 20, 'name' => 'Ou Ya Dav'],
            ['id' => 154, 'province_id' => 20, 'name' => 'Ta Veaeng'],
            ['id' => 155, 'province_id' => 20, 'name' => 'Veun Sai'],
            ['id' => 156, 'province_id' => 21, 'name' => 'Angkor Chum'],
            ['id' => 157, 'province_id' => 21, 'name' => 'Angkor Thum'],
            ['id' => 158, 'province_id' => 21, 'name' => 'Banteay Srei'],
            ['id' => 159, 'province_id' => 21, 'name' => 'Chi Kraeng'],
            ['id' => 160, 'province_id' => 21, 'name' => 'Kralanh'],
            ['id' => 161, 'province_id' => 21, 'name' => 'Puok'],
            ['id' => 162, 'province_id' => 21, 'name' => 'Prasat Bakong'],
            ['id' => 163, 'province_id' => 21, 'name' => 'Siem Reap'],
            ['id' => 164, 'province_id' => 21, 'name' => 'Soutr Nikom'],
            ['id' => 165, 'province_id' => 21, 'name' => 'Srei Snam'],
            ['id' => 166, 'province_id' => 21, 'name' => 'Svay Leu'],
            ['id' => 167, 'province_id' => 21, 'name' => 'Veun Sai'],
            ['id' => 168, 'province_id' => 22, 'name' => 'Sesan'],
            ['id' => 169, 'province_id' => 22, 'name' => 'Siem Bouk'],
            ['id' => 170, 'province_id' => 22, 'name' => 'Siem Pang'],
            ['id' => 171, 'province_id' => 22, 'name' => 'Stueng Traeng'],
            ['id' => 172, 'province_id' => 22, 'name' => 'Thala Barivat'],
            ['id' => 173, 'province_id' => 23, 'name' => 'Chantrea'],
            ['id' => 174, 'province_id' => 23, 'name' => 'Kampong Rou'],
            ['id' => 175, 'province_id' => 23, 'name' => 'Rumduol'],
            ['id' => 176, 'province_id' => 23, 'name' => 'Romeas Haek'],
            ['id' => 177, 'province_id' => 23, 'name' => 'Svay Chrum'],
            ['id' => 178, 'province_id' => 23, 'name' => 'Svay Rieng'],
            ['id' => 179, 'province_id' => 23, 'name' => 'Svay Teab'],
            ['id' => 180, 'province_id' => 23, 'name' => 'Bavet'],
            ['id' => 181, 'province_id' => 24, 'name' => 'Angkor Borei'],
            ['id' => 182, 'province_id' => 24, 'name' => 'Bati'],
            ['id' => 183, 'province_id' => 24, 'name' => 'Borei Cholsar'],
            ['id' => 184, 'province_id' => 24, 'name' => 'Borei Cholsar'],
            ['id' => 185, 'province_id' => 24, 'name' => 'Kaoh Andaet'],
            ['id' => 186, 'province_id' => 24, 'name' => 'Prey Kabbas'],
            ['id' => 187, 'province_id' => 24, 'name' => 'Samraong'],
            ['id' => 188, 'province_id' => 24, 'name' => 'Doun Kaev'],
            ['id' => 189, 'province_id' => 24, 'name' => 'Tram Kak'],
            ['id' => 110, 'province_id' => 24, 'name' => 'Treang'],
            ['id' => 190, 'province_id' => 25, 'name' => 'Dambae'],
            ['id' => 191, 'province_id' => 25, 'name' => 'Krouch Chhmar'],
            ['id' => 192, 'province_id' => 25, 'name' => 'Memot'],
            ['id' => 193, 'province_id' => 25, 'name' => 'Ou Reang Ov'],
            ['id' => 194, 'province_id' => 25, 'name' => 'Ponhea Kraek'],
            ['id' => 195, 'province_id' => 25, 'name' => 'Suong'],
            ['id' => 196, 'province_id' => 25, 'name' => 'Tboung Khmum'],

        ];
        foreach ($districts as $district) {
            District::create($district);
        }
    }
}
