<?php

namespace Database\Seeders;

use App\Models\Village;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class VillageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $villages = [
            ['id' => 1, 'commune_id' => 1, 'name' => 'Phum 1'],
            ['id' => 2, 'commune_id' => 1, 'name' => 'Phum 2'],
            ['id' => 3, 'commune_id' => 1, 'name' => 'Phum 3'],
            ['id' => 4, 'commune_id' => 1, 'name' => 'Phum 4'],
            ['id' => 5, 'commune_id' => 1, 'name' => 'Phum 5'],
            ['id' => 6, 'commune_id' => 1, 'name' => 'Phum 6'],
            ['id' => 7, 'commune_id' => 1, 'name' => 'Phum 7'],
            ['id' => 8, 'commune_id' => 1, 'name' => 'Phum 8'],
            ['id' => 9, 'commune_id' => 1, 'name' => 'Phum 9'],
            ['id' => 10, 'commune_id' => 1, 'name' => 'Phum 10'],
            ['id' => 11, 'commune_id' => 1, 'name' => 'Phum 11'],
            ['id' => 12, 'commune_id' => 1, 'name' => 'Phum 12'],
            ['id' => 13, 'commune_id' => 1, 'name' => 'Phum 13'],
            ['id' => 14, 'commune_id' => 1, 'name' => 'Phum 14'],
            ['id' => 15, 'commune_id' => 1, 'name' => 'Phum 15'],
            ['id' => 16, 'commune_id' => 1, 'name' => 'Phum 16'],
            ['id' => 17, 'commune_id' => 2, 'name' => 'Phum 1'],
            ['id' => 18, 'commune_id' => 2, 'name' => 'Phum 2'],
            ['id' => 19, 'commune_id' => 2, 'name' => 'Phum 3'],
            ['id' => 20, 'commune_id' => 2, 'name' => 'Phum 4'],
            ['id' => 21, 'commune_id' => 2, 'name' => 'Phum 5'],
            ['id' => 22, 'commune_id' => 2, 'name' => 'Phum 6'],
            ['id' => 23, 'commune_id' => 2, 'name' => 'Phum 7'],
            ['id' => 24, 'commune_id' => 2, 'name' => 'Phum 8'],
            ['id' => 25, 'commune_id' => 3, 'name' => 'Phum 1'],
            ['id' => 26, 'commune_id' => 3, 'name' => 'Phum 2'],
            ['id' => 27, 'commune_id' => 3, 'name' => 'Phum 3'],
            ['id' => 28, 'commune_id' => 3, 'name' => 'Phum 4'],
            ['id' => 29, 'commune_id' => 3, 'name' => 'Phum 5'],
            ['id' => 30, 'commune_id' => 3, 'name' => 'Phum 6'],
            ['id' => 31, 'commune_id' => 3, 'name' => 'Phum 7'],
            ['id' => 31, 'commune_id' => 4, 'name' => 'Phum 1'],
            ['id' => 33, 'commune_id' => 4, 'name' => 'Phum 2'],
            ['id' => 34, 'commune_id' => 4, 'name' => 'Phum 3'],
            ['id' => 35, 'commune_id' => 4, 'name' => 'Phum 4'],
            ['id' => 36, 'commune_id' => 4, 'name' => 'Phum 5'],
            ['id' => 37, 'commune_id' => 5, 'name' => 'Phum 1'],
            ['id' => 38, 'commune_id' => 5, 'name' => 'Phum 2'],
            ['id' => 39, 'commune_id' => 5, 'name' => 'Phum 3'],
            ['id' => 40, 'commune_id' => 5, 'name' => 'Phum 4'],
            ['id' => 41, 'commune_id' => 6, 'name' => 'Phum 1'],
            ['id' => 42, 'commune_id' => 6, 'name' => 'Phum 2'],
            ['id' => 43, 'commune_id' => 6, 'name' => 'Phum 3'],
            ['id' => 44, 'commune_id' => 6, 'name' => 'Phum 4'],
            ['id' => 45, 'commune_id' => 6, 'name' => 'Phum 5'],
            ['id' => 46, 'commune_id' => 6, 'name' => 'Phum 6'],
            ['id' => 47, 'commune_id' => 6, 'name' => 'Phum 7'],
            ['id' => 48, 'commune_id' => 6, 'name' => 'Phum 8'],
            ['id' => 49, 'commune_id' => 6, 'name' => 'Phum 9'],
            ['id' => 50, 'commune_id' => 6, 'name' => 'Phum 10'],
            ['id' => 51, 'commune_id' => 6, 'name' => 'Phum 11'],
            ['id' => 52, 'commune_id' => 6, 'name' => 'Phum 12'],
            ['id' => 53, 'commune_id' => 6, 'name' => 'Phum 13'],
            ['id' => 54, 'commune_id' => 6, 'name' => 'Phum 14'],
            ['id' => 55, 'commune_id' => 6, 'name' => 'Phum 15'],
            ['id' => 56, 'commune_id' => 6, 'name' => 'Phum 16'],
            ['id' => 57, 'commune_id' => 6, 'name' => 'Phum 17'],
            ['id' => 58, 'commune_id' => 6, 'name' => 'Phum 18'],
            ['id' => 59, 'commune_id' => 6, 'name' => 'Phum 19'],
            ['id' => 60, 'commune_id' => 6, 'name' => 'Phum 20'],
            ['id' => 61, 'commune_id' => 6, 'name' => 'Phum 21'],
            ['id' => 62, 'commune_id' => 6, 'name' => 'Phum 22'],
            ['id' => 63, 'commune_id' => 6, 'name' => 'Phum 23'],
            ['id' => 64, 'commune_id' => 6, 'name' => 'Phum 24'],
            ['id' => 65, 'commune_id' => 7, 'name' => 'Phum 1'],
            ['id' => 66, 'commune_id' => 7, 'name' => 'Phum 2'],
            ['id' => 67, 'commune_id' => 7, 'name' => 'Phum 3'],
            ['id' => 68, 'commune_id' => 7, 'name' => 'Phum 4'],
            ['id' => 69, 'commune_id' => 7, 'name' => 'Phum 5'],
            ['id' => 71, 'commune_id' => 7, 'name' => 'Phum 6'],
            ['id' => 71, 'commune_id' => 7, 'name' => 'Phum 7'],
            ['id' => 72, 'commune_id' => 7, 'name' => 'Phum 8'],
            ['id' => 73, 'commune_id' => 7, 'name' => 'Phum 9'],
            ['id' => 74, 'commune_id' => 7, 'name' => 'Phum 10'],
            ['id' => 75, 'commune_id' => 8, 'name' => 'Phum 1'],
            ['id' => 76, 'commune_id' => 8, 'name' => 'Phum 2'],
            ['id' => 77, 'commune_id' => 8, 'name' => 'Phum 3'],
            ['id' => 78, 'commune_id' => 8, 'name' => 'Phum 4'],
            ['id' => 79, 'commune_id' => 8, 'name' => 'Phum 5'],
            ['id' => 80, 'commune_id' => 8, 'name' => 'Phum 6'],
            ['id' => 81, 'commune_id' => 8, 'name' => 'Phum 7'],
            ['id' => 82, 'commune_id' => 8, 'name' => 'Phum 8'],
            ['id' => 83, 'commune_id' => 8, 'name' => 'Phum 9'],
            ['id' => 84, 'commune_id' => 8, 'name' => 'Phum 10'],
            ['id' => 85, 'commune_id' => 9, 'name' => 'Phum 1'],
            ['id' => 86, 'commune_id' => 9, 'name' => 'Phum 2'],
            ['id' => 87, 'commune_id' => 9, 'name' => 'Phum 3'],
            ['id' => 88, 'commune_id' => 9, 'name' => 'Phum 4'],
            ['id' => 89, 'commune_id' => 9, 'name' => 'Phum 5'],
            ['id' => 90, 'commune_id' => 10, 'name' => 'Phum 1'],
            ['id' => 91, 'commune_id' => 10, 'name' => 'Phum 2'],
            ['id' => 92, 'commune_id' => 10, 'name' => 'Phum 3'],
            ['id' => 93, 'commune_id' => 10, 'name' => 'Phum 4'],
            ['id' => 94, 'commune_id' => 10, 'name' => 'Phum 5'],
            ['id' => 95, 'commune_id' => 10, 'name' => 'Phum 6'],
            ['id' => 96, 'commune_id' => 10, 'name' => 'Phum 7'],
            ['id' => 97, 'commune_id' => 10, 'name' => 'Phum 8'],
            ['id' => 98, 'commune_id' => 10, 'name' => 'Phum 9'],
            ['id' => 99, 'commune_id' => 10, 'name' => 'Phum 10'],
            ['id' => 100, 'commune_id' => 10, 'name' => 'Phum 11'],
            ['id' => 101, 'commune_id' => 11, 'name' => 'Phum 1'],
            ['id' => 102, 'commune_id' => 11, 'name' => 'Phum 2'],
            ['id' => 103, 'commune_id' => 11, 'name' => 'Phum 3'],
            ['id' => 104, 'commune_id' => 11, 'name' => 'Phum 4'],
            ['id' => 105, 'commune_id' => 11, 'name' => 'Phum 5'],
            ['id' => 106, 'commune_id' => 11, 'name' => 'Phum 6'],
            ['id' => 107, 'commune_id' => 11, 'name' => 'Phum 7'],
            ['id' => 108, 'commune_id' => 11, 'name' => 'Phum 8'],
            ['id' => 109, 'commune_id' => 11, 'name' => 'Phum 10'],
            ['id' => 110, 'commune_id' => 11, 'name' => 'Phum 11'],
            ['id' => 111, 'commune_id' => 12, 'name' => 'Phum 1'],
            ['id' => 112, 'commune_id' => 12, 'name' => 'Phum 2'],
            ['id' => 113, 'commune_id' => 12, 'name' => 'Phum 3'],
            ['id' => 114, 'commune_id' => 12, 'name' => 'Phum 4'],
            ['id' => 115, 'commune_id' => 12, 'name' => 'Phum 5'],
            ['id' => 116, 'commune_id' => 12, 'name' => 'Phum 6'],
            ['id' => 117, 'commune_id' => 12, 'name' => 'Phum 7'],
            ['id' => 118, 'commune_id' => 12, 'name' => 'Phum 8'],
            ['id' => 119, 'commune_id' => 13, 'name' => 'Phum 1'],
            ['id' => 120, 'commune_id' => 13, 'name' => 'Phum 2'],
            ['id' => 121, 'commune_id' => 13, 'name' => 'Phum 3'],
            ['id' => 122, 'commune_id' => 13, 'name' => 'Phum 4'],
            ['id' => 123, 'commune_id' => 13, 'name' => 'Phum 5'],
            ['id' => 124, 'commune_id' => 13, 'name' => 'Phum 6'],
            ['id' => 125, 'commune_id' => 13, 'name' => 'Phum 7'],
            ['id' => 126, 'commune_id' => 13, 'name' => 'Phum 8'],
            ['id' => 127, 'commune_id' => 13, 'name' => 'Phum 9'],
            ['id' => 128, 'commune_id' => 13, 'name' => 'Phum 10'],
            ['id' => 129, 'commune_id' => 13, 'name' => 'Phum 11'],
            ['id' => 130, 'commune_id' => 14, 'name' => 'Phum 1'],
            ['id' => 131, 'commune_id' => 14, 'name' => 'Phum 2'],
            ['id' => 132, 'commune_id' => 14, 'name' => 'Phum 3'],
            ['id' => 133, 'commune_id' => 14, 'name' => 'Phum 4'],
            ['id' => 134, 'commune_id' => 14, 'name' => 'Phum 5'],
            ['id' => 135, 'commune_id' => 14, 'name' => 'Phum 6'],
            ['id' => 136, 'commune_id' => 14, 'name' => 'Phum 7'],
            ['id' => 137, 'commune_id' => 14, 'name' => 'Phum 8'],
            ['id' => 138, 'commune_id' => 14, 'name' => 'Phum 9'],
            ['id' => 139, 'commune_id' => 15, 'name' => 'Phum 1'],
            ['id' => 140, 'commune_id' => 15, 'name' => 'Phum 2'],
            ['id' => 141, 'commune_id' => 15, 'name' => 'Phum 3'],
            ['id' => 142, 'commune_id' => 15, 'name' => 'Phum 4'],
            ['id' => 143, 'commune_id' => 15, 'name' => 'Phum 5'],
            ['id' => 144, 'commune_id' => 15, 'name' => 'Phum 6'],
            ['id' => 145, 'commune_id' => 15, 'name' => 'Phum 7'],
            ['id' => 146, 'commune_id' => 15, 'name' => 'Phum 8'],
            ['id' => 147, 'commune_id' => 15, 'name' => 'Phum 9'],
            ['id' => 148, 'commune_id' => 16, 'name' => 'Phum 1'],
            ['id' => 149, 'commune_id' => 16, 'name' => 'Phum 2'],
            ['id' => 150, 'commune_id' => 16, 'name' => 'Phum 3'],
            ['id' => 151, 'commune_id' => 16, 'name' => 'Phum 4'],
            ['id' => 152, 'commune_id' => 16, 'name' => 'Phum 5'],
            ['id' => 153, 'commune_id' => 16, 'name' => 'Phum 6'],
            ['id' => 154, 'commune_id' => 16, 'name' => 'Phum 7'],
            ['id' => 155, 'commune_id' => 16, 'name' => 'Phum 8'],
            ['id' => 156, 'commune_id' => 16, 'name' => 'Phum 9'],
            ['id' => 157, 'commune_id' => 17, 'name' => 'Phum 1'],
            ['id' => 158, 'commune_id' => 17, 'name' => 'Phum 2'],
            ['id' => 159, 'commune_id' => 17, 'name' => 'Phum 3'],
            ['id' => 160, 'commune_id' => 17, 'name' => 'Phum 4'],
            ['id' => 161, 'commune_id' => 17, 'name' => 'Phum 5'],
            ['id' => 162, 'commune_id' => 17, 'name' => 'Phum 6'],
            ['id' => 163, 'commune_id' => 17, 'name' => 'Phum 7'],
            ['id' => 164, 'commune_id' => 17, 'name' => 'Phum 8'],
            ['id' => 165, 'commune_id' => 17, 'name' => 'Phum 9'],
            ['id' => 166, 'commune_id' => 18, 'name' => 'Phum 1'],
            ['id' => 167, 'commune_id' => 18, 'name' => 'Phum 2'],
            ['id' => 168, 'commune_id' => 18, 'name' => 'Phum 3'],
            ['id' => 169, 'commune_id' => 18, 'name' => 'Phum 4'],
            ['id' => 170, 'commune_id' => 18, 'name' => 'Phum 5'],
            ['id' => 171, 'commune_id' => 18, 'name' => 'Phum 6'],
            ['id' => 172, 'commune_id' => 18, 'name' => 'Phum 7'],
            ['id' => 173, 'commune_id' => 18, 'name' => 'Phum 8'],
            ['id' => 174, 'commune_id' => 18, 'name' => 'Phum 9'],
            ['id' => 175, 'commune_id' => 18, 'name' => 'Phum 10'],
            ['id' => 176, 'commune_id' => 19, 'name' => 'Phum 1'],
            ['id' => 177, 'commune_id' => 19, 'name' => 'Phum 2'],
            ['id' => 178, 'commune_id' => 19, 'name' => 'Phum 3'],
            ['id' => 179, 'commune_id' => 19, 'name' => 'Phum 4'],
            ['id' => 180, 'commune_id' => 19, 'name' => 'Phum 5'],
            ['id' => 181, 'commune_id' => 19, 'name' => 'Phum 6'],
            ['id' => 182, 'commune_id' => 19, 'name' => 'Phum 7'],
            ['id' => 183, 'commune_id' => 19, 'name' => 'Phum 8'],
            ['id' => 184, 'commune_id' => 19, 'name' => 'Phum 9'],
            ['id' => 185, 'commune_id' => 19, 'name' => 'Phum 10'],
            ['id' => 186, 'commune_id' => 19, 'name' => 'Phum 11'],
            ['id' => 187, 'commune_id' => 19, 'name' => 'Phum 12'],
            ['id' => 188, 'commune_id' => 20, 'name' => 'Phum 1'],
            ['id' => 189, 'commune_id' => 20, 'name' => 'Phum 2'],
            ['id' => 190, 'commune_id' => 20, 'name' => 'Phum 3'],
            ['id' => 191, 'commune_id' => 20, 'name' => 'Phum 4'],
            ['id' => 192, 'commune_id' => 20, 'name' => 'Phum 5'],
            ['id' => 193, 'commune_id' => 20, 'name' => 'Phum 6'],
            ['id' => 194, 'commune_id' => 21, 'name' => 'Phum 1'],
            ['id' => 195, 'commune_id' => 21, 'name' => 'Phum 2'],
            ['id' => 196, 'commune_id' => 21, 'name' => 'Phum 3'],
            ['id' => 197, 'commune_id' => 21, 'name' => 'Phum 4'],
            ['id' => 198, 'commune_id' => 21, 'name' => 'Phum 5'],
            ['id' => 199, 'commune_id' => 21, 'name' => 'Phum 6'],
            ['id' => 200, 'commune_id' => 21, 'name' => 'Phum 7'],
            ['id' => 201, 'commune_id' => 21, 'name' => 'Phum 8'],
            ['id' => 202, 'commune_id' => 21, 'name' => 'Phum 9'],
            ['id' => 203, 'commune_id' => 22, 'name' => 'Phum 1'],
            ['id' => 204, 'commune_id' => 22, 'name' => 'Phum 2'],
            ['id' => 205, 'commune_id' => 22, 'name' => 'Phum 3'],
            ['id' => 206, 'commune_id' => 22, 'name' => 'Phum 4'],
            ['id' => 207, 'commune_id' => 22, 'name' => 'Phum 5'],
            ['id' => 208, 'commune_id' => 22, 'name' => 'Phum 6'],
            ['id' => 209, 'commune_id' => 23, 'name' => 'Phum 1'],
            ['id' => 210, 'commune_id' => 23, 'name' => 'Phum 2'],
            ['id' => 211, 'commune_id' => 23, 'name' => 'Phum 3'],
            ['id' => 212, 'commune_id' => 23, 'name' => 'Phum 4'],
            ['id' => 213, 'commune_id' => 23, 'name' => 'Phum 5'],
            ['id' => 214, 'commune_id' => 23, 'name' => 'Phum 6'],
            ['id' => 215, 'commune_id' => 23, 'name' => 'Phum 7'],
            ['id' => 216, 'commune_id' => 23, 'name' => 'Phum 8'],
            ['id' => 217, 'commune_id' => 24, 'name' => 'Phum 1'],
            ['id' => 218, 'commune_id' => 24, 'name' => 'Phum 2'],
            ['id' => 219, 'commune_id' => 24, 'name' => 'Phum 3'],
            ['id' => 220, 'commune_id' => 24, 'name' => 'Phum 4'],
            ['id' => 221, 'commune_id' => 24, 'name' => 'Phum 5'],
            ['id' => 222, 'commune_id' => 24, 'name' => 'Phum 6'],
            ['id' => 223, 'commune_id' => 24, 'name' => 'Phum 7'],
            ['id' => 224, 'commune_id' => 24, 'name' => 'Phum 8'],
            ['id' => 225, 'commune_id' => 24, 'name' => 'Phum 9'],
            ['id' => 226, 'commune_id' => 24, 'name' => 'Phum 10'],
            ['id' => 227, 'commune_id' => 25, 'name' => 'Phum 1'],
            ['id' => 228, 'commune_id' => 25, 'name' => 'Phum 2'],
            ['id' => 229, 'commune_id' => 25, 'name' => 'Phum 3'],
            ['id' => 230, 'commune_id' => 25, 'name' => 'Phum 4'],
            ['id' => 231, 'commune_id' => 25, 'name' => 'Phum 5'],
            ['id' => 232, 'commune_id' => 25, 'name' => 'Phum 6'],
            ['id' => 233, 'commune_id' => 25, 'name' => 'Phum 7'],
            ['id' => 234, 'commune_id' => 25, 'name' => 'Phum 8'],
            ['id' => 235, 'commune_id' => 25, 'name' => 'Phum 9'],
            ['id' => 236, 'commune_id' => 25, 'name' => 'Phum 10'],
            ['id' => 237, 'commune_id' => 25, 'name' => 'Phum 11'],
            ['id' => 238, 'commune_id' => 26, 'name' => 'Phum 1'],
            ['id' => 239, 'commune_id' => 26, 'name' => 'Phum 2'],
            ['id' => 240, 'commune_id' => 26, 'name' => 'Phum 3'],
            ['id' => 241, 'commune_id' => 26, 'name' => 'Phum 4'],
            ['id' => 242, 'commune_id' => 26, 'name' => 'Phum 5'],
            ['id' => 243, 'commune_id' => 26, 'name' => 'Phum 6'],
            ['id' => 244, 'commune_id' => 26, 'name' => 'Phum 7'],
            ['id' => 245, 'commune_id' => 26, 'name' => 'Phum 8'],
            ['id' => 246, 'commune_id' => 26, 'name' => 'Phum 9'],
            ['id' => 247, 'commune_id' => 26, 'name' => 'Phum 10'],
            ['id' => 248, 'commune_id' => 27, 'name' => 'Phum 1'],
            ['id' => 249, 'commune_id' => 27, 'name' => 'Phum 2'],
            ['id' => 250, 'commune_id' => 27, 'name' => 'Phum 3'],
            ['id' => 251, 'commune_id' => 27, 'name' => 'Phum 4'],
            ['id' => 252, 'commune_id' => 27, 'name' => 'Phum 5'],
            ['id' => 253, 'commune_id' => 27, 'name' => 'Phum 6'],
            ['id' => 254, 'commune_id' => 27, 'name' => 'Phum 7'],
            ['id' => 255, 'commune_id' => 27, 'name' => 'Phum 8'],
            ['id' => 256, 'commune_id' => 27, 'name' => 'Phum 9'],
            ['id' => 257, 'commune_id' => 27, 'name' => 'Phum 10'],
            ['id' => 258, 'commune_id' => 27, 'name' => 'Phum 11'],
            ['id' => 259, 'commune_id' => 27, 'name' => 'Phum 12'],
            ['id' => 260, 'commune_id' => 27, 'name' => 'Phum 13'],
            ['id' => 261, 'commune_id' => 27, 'name' => 'Phum 14'],
            ['id' => 262, 'commune_id' => 27, 'name' => 'Phum 15'],
            ['id' => 263, 'commune_id' => 27, 'name' => 'Phum 16'],
            ['id' => 264, 'commune_id' => 28, 'name' => 'Phum 1'],
            ['id' => 265, 'commune_id' => 28, 'name' => 'Phum 2'],
            ['id' => 266, 'commune_id' => 28, 'name' => 'Phum 3'],
            ['id' => 267, 'commune_id' => 28, 'name' => 'Phum 4'],
            ['id' => 268, 'commune_id' => 28, 'name' => 'Phum 5'],
            ['id' => 269, 'commune_id' => 28, 'name' => 'Phum 6'],
            ['id' => 270, 'commune_id' => 28, 'name' => 'Phum 7'],
            ['id' => 271, 'commune_id' => 28, 'name' => 'Phum 8'],
            ['id' => 272, 'commune_id' => 28, 'name' => 'Phum 9'],
            ['id' => 273, 'commune_id' => 28, 'name' => 'Phum 10'],
            ['id' => 274, 'commune_id' => 28, 'name' => 'Phum 11'],
            ['id' => 275, 'commune_id' => 28, 'name' => 'Phum 12'],
            ['id' => 276, 'commune_id' => 28, 'name' => 'Phum 13'],
            ['id' => 277, 'commune_id' => 29, 'name' => 'Phum 1'],
            ['id' => 278, 'commune_id' => 29, 'name' => 'Phum 2'],
            ['id' => 279, 'commune_id' => 29, 'name' => 'Phum 3'],
            ['id' => 280, 'commune_id' => 29, 'name' => 'Phum 4'],
            ['id' => 281, 'commune_id' => 29, 'name' => 'Phum 5'],
            ['id' => 282, 'commune_id' => 29, 'name' => 'Phum 6'],
            ['id' => 283, 'commune_id' => 29, 'name' => 'Phum 7'],
            ['id' => 284, 'commune_id' => 29, 'name' => 'Phum 8'],
            ['id' => 285, 'commune_id' => 29, 'name' => 'Phum 9'],
            ['id' => 286, 'commune_id' => 29, 'name' => 'Phum 10'],
            ['id' => 287, 'commune_id' => 29, 'name' => 'Phum 11'],
            ['id' => 288, 'commune_id' => 29, 'name' => 'Phum 12'],
            ['id' => 289, 'commune_id' => 29, 'name' => 'Phum 13'],
            ['id' => 290, 'commune_id' => 30, 'name' => 'Phum 1'],
            ['id' => 291, 'commune_id' => 30, 'name' => 'Phum 2'],
            ['id' => 292, 'commune_id' => 30, 'name' => 'Phum 3'],
            ['id' => 293, 'commune_id' => 30, 'name' => 'Phum 4'],
            ['id' => 294, 'commune_id' => 30, 'name' => 'Phum 5'],
            ['id' => 295, 'commune_id' => 30, 'name' => 'Phum 6'],
            ['id' => 296, 'commune_id' => 30, 'name' => 'Phum 7'],
            ['id' => 297, 'commune_id' => 30, 'name' => 'Phum 8'],
            ['id' => 298, 'commune_id' => 30, 'name' => 'Phum 9'],
            ['id' => 299, 'commune_id' => 30, 'name' => 'Phum 10'],
            ['id' => 300, 'commune_id' => 30, 'name' => 'Phum 11'],
            ['id' => 301, 'commune_id' => 30, 'name' => 'Phum 12'],
            ['id' => 302, 'commune_id' => 30, 'name' => 'Phum 13'],
            ['id' => 303, 'commune_id' => 30, 'name' => 'Phum 14'],
            ['id' => 304, 'commune_id' => 31, 'name' => 'Phum 1'],
            ['id' => 305, 'commune_id' => 31, 'name' => 'Phum 2'],
            ['id' => 306, 'commune_id' => 31, 'name' => 'Phum 3'],
            ['id' => 307, 'commune_id' => 31, 'name' => 'Phum 4'],
            ['id' => 308, 'commune_id' => 31, 'name' => 'Phum 5'],
            ['id' => 308, 'commune_id' => 31, 'name' => 'Phum 6'],
            ['id' => 310, 'commune_id' => 31, 'name' => 'Phum 7'],
            ['id' => 311, 'commune_id' => 31, 'name' => 'Phum 8'],
            ['id' => 312, 'commune_id' => 31, 'name' => 'Phum 9'],
            ['id' => 313, 'commune_id' => 31, 'name' => 'Phum 10'],
            ['id' => 314, 'commune_id' => 31, 'name' => 'Phum 11'],
            ['id' => 315, 'commune_id' => 31, 'name' => 'Phum 12'],
            ['id' => 316, 'commune_id' => 31, 'name' => 'Phum 13'],
            ['id' => 317, 'commune_id' => 31, 'name' => 'Phum 14'],
            ['id' => 318, 'commune_id' => 31, 'name' => 'Phum 15'],
            ['id' => 319, 'commune_id' => 31, 'name' => 'Phum 16'],
            ['id' => 320, 'commune_id' => 31, 'name' => 'Phum 17'],
            ['id' => 321, 'commune_id' => 31, 'name' => 'Phum 18'],
            ['id' => 322, 'commune_id' => 31, 'name' => 'Phum 19'],
            ['id' => 323, 'commune_id' => 31, 'name' => 'Phum 20'],
            ['id' => 324, 'commune_id' => 31, 'name' => 'Phum 21'],
            ['id' => 325, 'commune_id' => 31, 'name' => 'Phum 22'],
            ['id' => 326, 'commune_id' => 31, 'name' => 'Phum 23'],
            ['id' => 327, 'commune_id' => 32, 'name' => 'Phum 1'],
            ['id' => 328, 'commune_id' => 32, 'name' => 'Phum 2'],
            ['id' => 329, 'commune_id' => 32, 'name' => 'Phum 3'],
            ['id' => 330, 'commune_id' => 32, 'name' => 'Phum 4'],
            ['id' => 331, 'commune_id' => 32, 'name' => 'Phum 5'],
            ['id' => 332, 'commune_id' => 32, 'name' => 'Phum 6'],
            ['id' => 333, 'commune_id' => 32, 'name' => 'Phum 7'],
            ['id' => 334, 'commune_id' => 32, 'name' => 'Phum 8'],
            ['id' => 335, 'commune_id' => 32, 'name' => 'Phum 9'],
            ['id' => 336, 'commune_id' => 32, 'name' => 'Phum 10'],
            ['id' => 337, 'commune_id' => 32, 'name' => 'Phum 11'],
            ['id' => 338, 'commune_id' => 32, 'name' => 'Phum 12'],
            ['id' => 339, 'commune_id' => 32, 'name' => 'Phum 13'],
            ['id' => 340, 'commune_id' => 32, 'name' => 'Phum 14'],
            ['id' => 341, 'commune_id' => 32, 'name' => 'Phum 16'],
            ['id' => 342, 'commune_id' => 32, 'name' => 'Phum 17'],
            ['id' => 343, 'commune_id' => 33, 'name' => 'Phum 1'],
            ['id' => 344, 'commune_id' => 33, 'name' => 'Phum 2'],
            ['id' => 345, 'commune_id' => 33, 'name' => 'Phum 3'],
            ['id' => 346, 'commune_id' => 33, 'name' => 'Phum 4'],
            ['id' => 347, 'commune_id' => 33, 'name' => 'Phum 5'],
            ['id' => 348, 'commune_id' => 33, 'name' => 'Phum 6'],
            ['id' => 349, 'commune_id' => 33, 'name' => 'Phum 7'],
            ['id' => 350, 'commune_id' => 33, 'name' => 'Phum 8'],
            ['id' => 351, 'commune_id' => 33, 'name' => 'Phum 9'],
            ['id' => 352, 'commune_id' => 33, 'name' => 'Phum 10'],
            ['id' => 353, 'commune_id' => 33, 'name' => 'Phum 11'],
            ['id' => 354, 'commune_id' => 33, 'name' => 'Phum 12'],
            ['id' => 355, 'commune_id' => 33, 'name' => 'Phum 13'],
            ['id' => 356, 'commune_id' => 33, 'name' => 'Phum 14'],
            ['id' => 357, 'commune_id' => 33, 'name' => 'Phum 15'],
            ['id' => 358, 'commune_id' => 33, 'name' => 'Phum 16'],
            ['id' => 359, 'commune_id' => 33, 'name' => 'Phum 17'],
            ['id' => 360, 'commune_id' => 34, 'name' => 'Thmei'],
            ['id' => 361, 'commune_id' => 34, 'name' => 'Baku'],
            ['id' => 362, 'commune_id' => 34, 'name' => 'Sambour'],
            ['id' => 363, 'commune_id' => 34, 'name' => 'Te lei'],
            ['id' => 364, 'commune_id' => 34, 'name' => 'Mol'],
            ['id' => 365, 'commune_id' => 34, 'name' => 'Khva'],
            ['id' => 366, 'commune_id' => 35, 'name' => 'Trapeang Tea'],
            ['id' => 367, 'commune_id' => 35, 'name' => 'Trapeang Kor'],
            ['id' => 368, 'commune_id' => 35, 'name' => 'Pong Tuek'],
            ['id' => 369, 'commune_id' => 35, 'name' => 'Voat Slaeng'],
            ['id' => 370, 'commune_id' => 35, 'name' => 'Srae Nhoar'],
            ['id' => 371, 'commune_id' => 35, 'name' => 'Khleah Sanday'],
            ['id' => 371, 'commune_id' => 35, 'name' => 'Prey Kei Kha'],
            ['id' => 372, 'commune_id' => 35, 'name' => 'Prey Kei Ka'],
            ['id' => 373, 'commune_id' => 35, 'name' => 'Trang Dao'],
            ['id' => 374, 'commune_id' => 35, 'name' => 'Trapeang Sala'],
            ['id' => 375, 'commune_id' => 36, 'name' => 'Prey Veaeng Khang Lech'],
            ['id' => 376, 'commune_id' => 36, 'name' => 'Prey Veaeng Khang Kaeut'],
            ['id' => 377, 'commune_id' => 36, 'name' => 'Trapeang Chak'],
            ['id' => 378, 'commune_id' => 36, 'name' => 'Trapeang Svay'],
            ['id' => 379, 'commune_id' => 36, 'name' => 'Toap Baoh'],
            ['id' => 380, 'commune_id' => 36, 'name' => 'Kamrieng'],
            ['id' => 381, 'commune_id' => 36, 'name' => 'Roul Chruk'],
            ['id' => 382, 'commune_id' => 36, 'name' => 'Serei Dei Doh'],
            ['id' => 383, 'commune_id' => 36, 'name' => 'Tuol Sambour'],
            ['id' => 384, 'commune_id' => 37, 'name' => 'Prey Thum'],
            ['id' => 385, 'commune_id' => 37, 'name' => 'Prey Sa Khang Kaeut'],
            ['id' => 386, 'commune_id' => 37, 'name' => 'Prakar'],
            ['id' => 388, 'commune_id' => 37, 'name' => 'Prey Sa Khang Lech'],
            ['id' => 389, 'commune_id' => 37, 'name' => 'Prey Tituy'],
            ['id' => 390, 'commune_id' => 37, 'name' => 'Anlong Kong'],
            ['id' => 391, 'commune_id' => 37, 'name' => 'Kouk Banteay'],
            ['id' => 392, 'commune_id' => 37, 'name' => 'Thommeak Trai'],
            ['id' => 393, 'commune_id' => 37, 'name' => 'Peam'],
            ['id' => 394, 'commune_id' => 37, 'name' => 'Mphey Buon'],
            ['id' => 395, 'commune_id' => 37, 'name' => 'Anlong Kong Thmei'],
            ['id' => 396, 'commune_id' => 37, 'name' => 'Tuol Roka Koh'],
            ['id' => 397, 'commune_id' => 38, 'name' => 'Krang Svay'],
            ['id' => 398, 'commune_id' => 38, 'name' => 'Krang Pongro'],
            ['id' => 399, 'commune_id' => 38, 'name' => 'Tuek Thla'],
            ['id' => 400, 'commune_id' => 38, 'name' => 'Prey Sampoar'],
            ['id' => 401, 'commune_id' => 39, 'name' => 'Prateah Lang'],
            ['id' => 402, 'commune_id' => 39, 'name' => 'Phea'],
            ['id' => 403, 'commune_id' => 39, 'name' => 'Angk'],
            ['id' => 404, 'commune_id' => 39, 'name' => 'Tang Roneam'],
            ['id' => 405, 'commune_id' => 39, 'name' => 'Kouk Khsach'],
            ['id' => 406, 'commune_id' => 39, 'name' => 'Kouk Meas'],
            ['id' => 407, 'commune_id' => 40, 'name' => 'Pou Rolum'],
            ['id' => 408, 'commune_id' => 40, 'name' => 'Khvet'],
            ['id' => 409, 'commune_id' => 40, 'name' => 'Krang Ta Phou'],
            ['id' => 410, 'commune_id' => 40, 'name' => 'Kamraeng'],
            ['id' => 411, 'commune_id' => 40, 'name' => 'Sambuor'],
            ['id' => 412, 'commune_id' => 41, 'name' => 'Cheung Aek'],
            ['id' => 413, 'commune_id' => 41, 'name' => 'Roluos'],
            ['id' => 414, 'commune_id' => 41, 'name' => 'Srok Chek'],
            ['id' => 415, 'commune_id' => 41, 'name' => 'Preaek Pranak'],
            ['id' => 416, 'commune_id' => 41, 'name' => 'Preaek Thloeng'],
            ['id' => 417, 'commune_id' => 42, 'name' => 'Kong Noy'],
            ['id' => 418, 'commune_id' => 42, 'name' => 'Veal Thlan'],
            ['id' => 419, 'commune_id' => 42, 'name' => 'Serei Sambatt'],
            ['id' => 420, 'commune_id' => 42, 'name' => 'Trapeang Samret'],
            ['id' => 421, 'commune_id' => 43, 'name' => 'Preaek Kampues'],
            ['id' => 422, 'commune_id' => 43, 'name' => 'Preaek Roteang'],
            ['id' => 423, 'commune_id' => 43, 'name' => 'Preaek Thloeng'],
            ['id' => 424, 'commune_id' => 43, 'name' => 'Damnak Sangkae'],
            ['id' => 425, 'commune_id' => 43, 'name' => 'Srei Snam'],
            ['id' => 426, 'commune_id' => 44, 'name' => 'Krapeu Troum'],
            ['id' => 427, 'commune_id' => 44, 'name' => 'Preah Theat'],
            ['id' => 428, 'commune_id' => 44, 'name' => 'Kandal'],
            ['id' => 429, 'commune_id' => 45, 'name' => 'Anhchanh'],
            ['id' => 429, 'commune_id' => 45, 'name' => 'Kouk Ovloek'],
            ['id' => 429, 'commune_id' => 45, 'name' => 'Meun Tra'],
            ['id' => 429, 'commune_id' => 45, 'name' => 'Spean Thma'],
            ['id' => 429, 'commune_id' => 45, 'name' => 'Svay Mean Leak'],
            ['id' => 430, 'commune_id' => 46, 'name' => 'Krang Krouch'],
            ['id' => 431, 'commune_id' => 46, 'name' => 'Thmei'],
            ['id' => 432, 'commune_id' => 46, 'name' => 'Thma'],
            ['id' => 433, 'commune_id' => 46, 'name' => 'Kantuy Tuek'],
            ['id' => 434, 'commune_id' => 46, 'name' => 'Sala'],
            ['id' => 435, 'commune_id' => 47, 'name' => 'Ruessei'],
            ['id' => 436, 'commune_id' => 47, 'name' => 'Mean Chey'],
            ['id' => 437, 'commune_id' => 47, 'name' => 'Prek Toal'],
            ['id' => 438, 'commune_id' => 47, 'name' => 'Russey Muoy'],
            ['id' => 439, 'commune_id' => 47, 'name' => 'Trea Muoy'],
            ['id' => 440, 'commune_id' => 48, 'name' => 'Chamraeun Phal'],
            ['id' => 441, 'commune_id' => 48, 'name' => 'Sansam Kosal Muoy'],
            ['id' => 442, 'commune_id' => 48, 'name' => 'Sansam Kosal Pir'],
            ['id' => 443, 'commune_id' => 48, 'name' => 'Kbal Tumnob'],
            ['id' => 444, 'commune_id' => 48, 'name' => 'Tnaot Chrum'],
            ['id' => 445, 'commune_id' => 49, 'name' => 'Prek Ta Kong'],
            ['id' => 446, 'commune_id' => 49, 'name' => 'Prek Ta Nu'],
            ['id' => 447, 'commune_id' => 49, 'name' => 'Prek Ta Kong I'],
            ['id' => 448, 'commune_id' => 49, 'name' => 'Prek Ta Kong II'],
            ['id' => 449, 'commune_id' => 49, 'name' => 'Prek Ta Kong III'],
            ['id' => 450, 'commune_id' => 50, 'name' => 'Tuol Roka'],
            ['id' => 451, 'commune_id' => 50, 'name' => 'Preaek Ta Long'],
            ['id' => 452, 'commune_id' => 50, 'name' => 'Tuol Roka Muoy'],
            ['id' => 453, 'commune_id' => 50, 'name' => 'Tuol Roka Pir'],
            ['id' => 454, 'commune_id' => 50, 'name' => 'Tuol Roka Bei'],
            ['id' => 455, 'commune_id' => 51, 'name' => 'Phsar Toch'],
            ['id' => 456, 'commune_id' => 51, 'name' => 'Toul sangke'],
            ['id' => 457, 'commune_id' => 51, 'name' => 'Tuol Kok'],
            ['id' => 458, 'commune_id' => 52, 'name' => 'La Kambaor'],
            ['id' => 459, 'commune_id' => 52, 'name' => 'Lu'],
            ['id' => 460, 'commune_id' => 52, 'name' => 'Svay Pak'],
            ['id' => 461, 'commune_id' => 53, 'name' => 'Kraol Kou'],
            ['id' => 462, 'commune_id' => 53, 'name' => 'Spean Khpos'],
            ['id' => 463, 'commune_id' => 53, 'name' => 'Boeng Chhuk'],
            ['id' => 464, 'commune_id' => 54, 'name' => 'Mittakpheap'],
            ['id' => 465, 'commune_id' => 54, 'name' => 'Sameakki'],
            ['id' => 466, 'commune_id' => 54, 'name' => 'Khleang Sang'],
            ['id' => 467, 'commune_id' => 54, 'name' => 'Boeng Salang'],
            ['id' => 468, 'commune_id' => 55, 'name' => 'Phum 1'],
            ['id' => 469, 'commune_id' => 55, 'name' => 'Phum 2'],
            ['id' => 470, 'commune_id' => 55, 'name' => 'Phum 3'],
            ['id' => 471, 'commune_id' => 55, 'name' => 'Phum 4'],
            ['id' => 472, 'commune_id' => 56, 'name' => 'Phum Ka'],
            ['id' => 473, 'commune_id' => 56, 'name' => 'Phum Kha Muoy'],
            ['id' => 474, 'commune_id' => 56, 'name' => 'Phum Kha Pir'],
            ['id' => 475, 'commune_id' => 56, 'name' => 'Phum Kho'],
            ['id' => 476, 'commune_id' => 57, 'name' => 'Chres'],
            ['id' => 477, 'commune_id' => 57, 'name' => 'Poung Peay'],
            ['id' => 478, 'commune_id' => 57, 'name' => 'Damnak'],
            ['id' => 479, 'commune_id' => 57, 'name' => 'Bayab'],
            ['id' => 480, 'commune_id' => 57, 'name' => 'Phnom Penh Thmei'],
            ['id' => 481, 'commune_id' => 58, 'name' => 'Ou Baek Kam'],
            ['id' => 482, 'commune_id' => 58, 'name' => 'Trapeang Chhuk'],
            ['id' => 483, 'commune_id' => 58, 'name' => 'Slaeng Roleung'],
            ['id' => 484, 'commune_id' => 58, 'name' => 'Phsar Tuek Thla'],
            ['id' => 485, 'commune_id' => 58, 'name' => 'Bourei Muoy Roy Khnang'],
            ['id' => 486, 'commune_id' => 59, 'name' => 'Anlong Kngan'],
            ['id' => 487, 'commune_id' => 59, 'name' => 'Banla Set'],
            ['id' => 488, 'commune_id' => 59, 'name' => 'Samraong'],
            ['id' => 489, 'commune_id' => 59, 'name' => 'Anlong Kngan'],
            ['id' => 490, 'commune_id' => 59, 'name' => 'Trapeang Reang'],
            ['id' => 491, 'commune_id' => 60, 'name' => 'Krang Angkrang'],
            ['id' => 492, 'commune_id' => 60, 'name' => 'Trapeang Mean'],
            ['id' => 493, 'commune_id' => 60, 'name' => 'Cheang Tong'],
            ['id' => 494, 'commune_id' => 60, 'name' => 'Trapeang Cheung Srok'],
            ['id' => 495, 'commune_id' => 60, 'name' => 'Prey Khla'],
            ['id' => 496, 'commune_id' => 61, 'name' => 'Aksar'],
            ['id' => 497, 'commune_id' => 61, 'name' => 'Krang'],
            ['id' => 498, 'commune_id' => 61, 'name' => 'Trapaang Andoung'],
            ['id' => 499, 'commune_id' => 61, 'name' => 'Prey Doun Ok'],
            ['id' => 500, 'commune_id' => 61, 'name' => 'Trapeang Tea'],
            ['id' => 501, 'commune_id' => 62, 'name' => 'Tuol Kei'],
            ['id' => 502, 'commune_id' => 62, 'name' => 'Kab Phluk'],
            ['id' => 503, 'commune_id' => 62, 'name' => 'Prey Rongieng'],
            ['id' => 504, 'commune_id' => 62, 'name' => 'Tranh Tabanh'],
            ['id' => 505, 'commune_id' => 62, 'name' => 'Phleung Chheh Roteh Lech'],
            ['id' => 506, 'commune_id' => 63, 'name' => 'Trapeang Pou'],
            ['id' => 507, 'commune_id' => 63, 'name' => 'Damnak Trayueng'],
            ['id' => 508, 'commune_id' => 63, 'name' => 'Kab Kong'],
            ['id' => 509, 'commune_id' => 63, 'name' => 'Prey Kambot'],
            ['id' => 510, 'commune_id' => 63, 'name' => 'Prey Spueu'],
            ['id' => 511, 'commune_id' => 64, 'name' => 'Prey Sala'],
            ['id' => 512, 'commune_id' => 64, 'name' => 'Kakab'],
            ['id' => 513, 'commune_id' => 64, 'name' => 'Trapeang Chrey'],
            ['id' => 514, 'commune_id' => 64, 'name' => 'Chamkar Ovloek'],
            ['id' => 515, 'commune_id' => 64, 'name' => 'Trapeang Lvea'],
            ['id' => 516, 'commune_id' => 65, 'name' => 'Chamkar Sbaeng'],
            ['id' => 517, 'commune_id' => 65, 'name' => 'Trapeang Thnong'],
            ['id' => 518, 'commune_id' => 65, 'name' => 'Kouk Prich'],
            ['id' => 519, 'commune_id' => 65, 'name' => 'Tekapanhao'],
            ['id' => 520, 'commune_id' => 65, 'name' => 'Samraong'],
            ['id' => 521, 'commune_id' => 66, 'name' => 'Tmat Pong'],
            ['id' => 522, 'commune_id' => 66, 'name' => 'Prey Romeas Ti Pir'],
            ['id' => 523, 'commune_id' => 66, 'name' => 'Prey Romeas Ti Muoy'],
            ['id' => 524, 'commune_id' => 66, 'name' => 'Ta Chet'],
            ['id' => 525, 'commune_id' => 66, 'name' => 'Boeng Thum Ti Muoy'],
            ['id' => 526, 'commune_id' => 67, 'name' => 'Phsar Kamboul'],
            ['id' => 527, 'commune_id' => 67, 'name' => 'Ta Ke'],
            ['id' => 528, 'commune_id' => 67, 'name' => 'Trapeang Tuol'],
            ['id' => 529, 'commune_id' => 67, 'name' => 'Kamboul'],
            ['id' => 530, 'commune_id' => 67, 'name' => 'Tuol Ta Lat'],
            ['id' => 531, 'commune_id' => 68, 'name' => 'Thma Da'],
            ['id' => 532, 'commune_id' => 68, 'name' => 'Trapeang Kol'],
            ['id' => 533, 'commune_id' => 68, 'name' => 'Snguon Pech'],
            ['id' => 534, 'commune_id' => 68, 'name' => 'Kantaok Tboun'],
            ['id' => 535, 'commune_id' => 68, 'name' => 'Kol'],
            ['id' => 536, 'commune_id' => 69, 'name' => 'Prey Ta Pok'],
            ['id' => 537, 'commune_id' => 69, 'name' => 'Trapeang Kak'],
            ['id' => 538, 'commune_id' => 69, 'name' => 'Angk Slaeng'],
            ['id' => 539, 'commune_id' => 69, 'name' => 'Doun Roatn'],
            ['id' => 540, 'commune_id' => 69, 'name' => 'Trapeang Areaks'],
            ['id' => 541, 'commune_id' => 70, 'name' => 'Sak Prayutth'],
            ['id' => 542, 'commune_id' => 70, 'name' => 'Angkor Chey'],
            ['id' => 543, 'commune_id' => 70, 'name' => 'Srae Ampil'],
            ['id' => 544, 'commune_id' => 70, 'name' => 'Ta En'],
            ['id' => 545, 'commune_id' => 70, 'name' => 'Kol Krasna'],
            ['id' => 546, 'commune_id' => 71, 'name' => 'Phum 1'],
            ['id' => 547, 'commune_id' => 71, 'name' => 'Phum 2'],
            ['id' => 548, 'commune_id' => 71, 'name' => 'Phum 3'],
            ['id' => 549, 'commune_id' => 71, 'name' => 'Daeum Kor'],
            ['id' => 550, 'commune_id' => 71, 'name' => 'Kien Khleang'],
            ['id' => 551, 'commune_id' => 72, 'name' => 'Kien Khleang'],
            ['id' => 552, 'commune_id' => 72, 'name' => 'Preaek Lieb'],
            ['id' => 553, 'commune_id' => 72, 'name' => 'Bak Khaeng'],
            ['id' => 554, 'commune_id' => 72, 'name' => 'Khtor'],
            ['id' => 555, 'commune_id' => 73, 'name' => 'Chong Kaoh'],
            ['id' => 556, 'commune_id' => 73, 'name' => 'Lvea'],
            ['id' => 557, 'commune_id' => 73, 'name' => 'Kbal Kaoh'],
            ['id' => 558, 'commune_id' => 73, 'name' => 'Kaoh Dach'],
            ['id' => 559, 'commune_id' => 73, 'name' => 'Roneah'],
            ['id' => 560, 'commune_id' => 74, 'name' => 'Bak Khaeng Leu'],
            ['id' => 561, 'commune_id' => 74, 'name' => 'Kdei Chas'],
            ['id' => 562, 'commune_id' => 74, 'name' => 'Chambak Meas'],
            ['id' => 563, 'commune_id' => 75, 'name' => 'Duong'],
            ['id' => 564, 'commune_id' => 75, 'name' => 'Pou Mongkol'],
            ['id' => 565, 'commune_id' => 75, 'name' => 'Preaek Pnov'],
            ['id' => 566, 'commune_id' => 75, 'name' => 'Phsar Lech'],
            ['id' => 567, 'commune_id' => 75, 'name' => 'Kandal'],
            ['id' => 568, 'commune_id' => 76, 'name' => 'Thum Tboung'],
            ['id' => 569, 'commune_id' => 76, 'name' => 'Thum Cheung'],
            ['id' => 570, 'commune_id' => 76, 'name' => 'Trapeang Snaor'],
            ['id' => 571, 'commune_id' => 76, 'name' => 'Boeng'],
            ['id' => 572, 'commune_id' => 76, 'name' => 'Trapeang Pring'],
            ['id' => 573, 'commune_id' => 77, 'name' => 'Kruos'],
            ['id' => 574, 'commune_id' => 77, 'name' => 'Samraong Cheung'],
            ['id' => 575, 'commune_id' => 77, 'name' => 'Samraong Kandal'],
            ['id' => 576, 'commune_id' => 77, 'name' => 'Samraong Tboung'],
            ['id' => 577, 'commune_id' => 78, 'name' => 'Kab Srov Touch'],
            ['id' => 578, 'commune_id' => 78, 'name' => 'Kab Srov Thum'],
            ['id' => 579, 'commune_id' => 78, 'name' => 'Svay Chek'],
            ['id' => 580, 'commune_id' => 78, 'name' => 'Baek Bak'],
            ['id' => 581, 'commune_id' => 78, 'name' => 'Trapeang Veaeng'],
            ['id' => 582, 'commune_id' => 79, 'name' => 'Buon Mukh'],
            ['id' => 583, 'commune_id' => 79, 'name' => 'Trapeang  Ampil'],
            ['id' => 584, 'commune_id' => 79, 'name' => 'Svay Otdam'],
            ['id' => 585, 'commune_id' => 79, 'name' => 'Thnal Banteay'],
            ['id' => 586, 'commune_id' => 79, 'name' => 'Trapeang Totueng'],
            ['id' => 587, 'commune_id' => 80, 'name' => 'Preaek'],
            ['id' => 588, 'commune_id' => 80, 'name' => 'Daeum Meakkloea'],
            ['id' => 589, 'commune_id' => 80, 'name' => 'Daeum Ampil'],
            ['id' => 590, 'commune_id' => 81, 'name' => 'Kandal'],
            ['id' => 591, 'commune_id' => 81, 'name' => 'Deum Slaeng'],
            ['id' => 592, 'commune_id' => 81, 'name' => 'Deum Chan I'],
            ['id' => 593, 'commune_id' => 81, 'name' => 'Kandal I'],
            ['id' => 594, 'commune_id' => 81, 'name' => 'Deum Slaeng I'],
            ['id' => 594, 'commune_id' => 81, 'name' => 'Deum Slaeng I'],
            ['id' => 595, 'commune_id' => 82, 'name' => 'Ta Ngov'],
            ['id' => 596, 'commune_id' => 82, 'name' => 'Boeng Chhuk'],
            ['id' => 597, 'commune_id' => 82, 'name' => 'Ruessei Sras'],
            ['id' => 598, 'commune_id' => 82, 'name' => 'Kaoh Norea'],
            ['id' => 599, 'commune_id' => 82, 'name' => 'Ta Ngov Kandal'],
            ['id' => 600, 'commune_id' => 83, 'name' => 'Chrouy Basak'],
            ['id' => 601, 'commune_id' => 83, 'name' => 'Preah Ponlea'],
            ['id' => 602, 'commune_id' => 83, 'name' => 'Preaek Ta Pov'],
            ['id' => 603, 'commune_id' => 83, 'name' => 'Ou Andoung'],
            ['id' => 604, 'commune_id' => 83, 'name' => 'Chrouy Basak Muoy'],
            ['id' => 605, 'commune_id' => 84, 'name' => 'Kdei Ta Koy'],
            ['id' => 606, 'commune_id' => 84, 'name' => 'Veal Sbov'],
            ['id' => 607, 'commune_id' => 84, 'name' => 'Svay Ta Ok'],
            ['id' => 608, 'commune_id' => 84, 'name' => 'Preaek Cheang Prum'],
            ['id' => 609, 'commune_id' => 84, 'name' => 'Svay Ta Ok 1'],
            ['id' => 610, 'commune_id' => 85, 'name' => 'Kbal Chrouy'],
            ['id' => 611, 'commune_id' => 85, 'name' => 'Ta Prum'],
            ['id' => 612, 'commune_id' => 85, 'name' => 'Mitakpheap'],
            ['id' => 613, 'commune_id' => 85, 'name' => 'Tuol Ta Chan'],
            ['id' => 614, 'commune_id' => 85, 'name' => 'Chong Preae'],
            ['id' => 615, 'commune_id' => 86, 'name' => 'Chrouy Ampil'],
            ['id' => 616, 'commune_id' => 86, 'name' => 'Yok Bat'],
            ['id' => 617, 'commune_id' => 86, 'name' => 'Preaek Thum'],
            ['id' => 618, 'commune_id' => 86, 'name' => 'Chrouy Ampil 1'],
            ['id' => 619, 'commune_id' => 86, 'name' => 'Chrouy Ampil 2'],
            ['id' => 620, 'commune_id' => 87, 'name' => 'Champuh Kaek'],
            ['id' => 621, 'commune_id' => 87, 'name' => 'Kaoh Krabei'],
            ['id' => 622, 'commune_id' => 87, 'name' => 'Preaek Thmei'],
            ['id' => 623, 'commune_id' => 87, 'name' => 'Champuh Kaek 1'],
            ['id' => 624, 'commune_id' => 87, 'name' => 'Kaoh Krabei 1'],
        ];
        foreach ($villages as $village) {
            Village::create($village);
        }
    }
}
